### ISSUE TITLE
Looking for more details about actual project scope

### ISSUE THREAD

**Issue by Zatvobor** [cogciprocate/ocl#1]
Hey. Just wondering, what's an actual project scope and purpose you have? That would be great to know (or have a strict explanation) the main difference between this project and https://github.com/luqmana/rust-opencl.

**Comment by c0gent** [comment]
Thanks for the feedback. I'll have to take a closer look at that project but I'm sure both projects do the same thing in slightly different ways. This project began as a module of another project over a year ago and I recently broke it out into it's own repo/crate just in case it might be useful to others. I'll add a section in the Readme about the goals of the project.

Any luck firing it up?

Keep the good feedback coming.

**Comment by Zatvobor** [comment]
Got it.
