### ISSUE TITLE
Seperate Development Branch

### ISSUE THREAD

**Issue by adamisntdead** [cogciprocate/ocl#100]
Just looking through the examples, and I tried to do them with a new project, but they didn't work.
Noticed that some of the changes are breaking, so it might be worthwhile separating the in-development version from the version currently on crates.io

**Comment by c0gent** [comment]
Not a bad idea. I may begin keeping a separate branch for the latest release. For now you can just [browse the repo](https://github.com/cogciprocate/ocl/tree/8eac16dc9483f5d5c0aa8d1a84abc1f715fec7e7) at the point of the [`Version 0.17.0` commit](https://github.com/cogciprocate/ocl/commit/8eac16dc9483f5d5c0aa8d1a84abc1f715fec7e7).
