### ISSUE TITLE
Support for Num_Complex

### ISSUE THREAD

**Issue by adamisntdead** [cogciprocate/ocl#102]
Do you have a way to pass arbitrary types to a buffer? Such as the `num_complex` type.

**Comment by c0gent** [comment]
The best way is to just lie when you're creating a buffer. For `num_complex` you could just say it's an [`ocl::core::Float2`](https://docs.rs/ocl-core/0.8.0/ocl_core/struct.Float2.html) or [`Double2`](https://docs.rs/ocl-core/0.8.0/ocl_core/struct.Double2.html) (depending on whether it was a `f32` or `f64` complex). Obviously the size/alignment/padding of the types must always match exactly.

```
let buffer: Buffer<ocl::core::Double2> = Buffer::builder()...
```

For weirdly sized structs or types you can lie and use bytes (`u8`). Be careful that you calculate the length/size correctly when doing this. Also be extremely careful with alignment, padding, etc., `#[repr(C)]` is not enough to ensure correct alignment (you may have to carefully pad structs manually).

Another option is just to use [`ocl::core::Mem`](https://docs.rs/ocl-core/0.8.0/ocl_core/types/abs/struct.Mem.html) directly. You can create one with the [`ocl::core::create_buffer`](https://docs.rs/ocl-core/0.8.0/ocl_core/fn.create_buffer.html) function and enqueue commands with [various enqueue functions](https://docs.rs/ocl-core/0.8.0/ocl_core/index.html?search=enqueue).

**Comment by c0gent** [comment]
I went ahead and [added support for the `num_complex` types](https://github.com/cogciprocate/ocl/commit/c345b5b01688fe7e9a085ab47d789a648c58550e) since the library uses some `num` crates anyway.

**Comment by adamisntdead** [comment]
Btw, when are you going to release the next version?

tysm!

**Comment by Kerollmops** [comment]
There is currently [a big rewrite](https://trello.com/b/kflyz03A/possible-improvements) of the lib but this will be the next major release.

**Comment by c0gent** [comment]
I'll probably publish the next version within a week or so if nothing else comes up.
