### ISSUE TITLE
no Kernel::builder function (examples out of date?)

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [cogciprocate/ocl#103]
Trying to follow the examples using version 0.17 but can't figure out how to build the kernel as there is no Kernel::builder function.

Are the examples out of date?

**Comment by Kerollmops** [comment]
You must use the [Kernel ocl 0.17 doc](https://docs.rs/ocl/0.17.0/ocl/struct.Kernel.html), current examples are to recent and concerns the future big ocl release.

**Comment by adamisntdead** [comment]
How far is the next version release?

**Comment by c0gent** [comment]
Next few days.

**Comment by PaperPlaneSoftware** [comment]
Oops, that would explain why it wasn't able to find the function. Thought I was looking at the docs for the version I was using. Thanks for pointing me in the right direction.
