### ISSUE TITLE
Expand info methods

### ISSUE THREAD

**Issue by JustAPerson** [cogciprocate/ocl#104]
So a lot of types have functions that take an `*Info` enum request and return a `*InfoResult` enum. Most of these (except for `Device`) have only a few variants. Would you accept a PR to replace these methods with one method for each variant of the enums?

**Comment by c0gent** [comment]
I've been thinking about doing this for quite a while. The main reason I haven't (besides the fact that it's quite a bit of work) is that it would add a considerable amount of UI bloat (particularly for `Device`) for a convenience that only an extremely tiny percentage of users will ever need.

If we did add it, it would need to be done properly, bypassing the `*Info`, `*InfoResult` stuff altogether and instead having a dedicated `ocl-core` function for each request type calling `clGet___Info` directly, passing the exact size of the return value in cases where it was known ahead of time (saving us having to call the function twice). Again, this would be potentially convenient for a few, but would add a lot of extra bloat.

I'm honestly torn on this. I'd like to hear more from other users before adding this. If you're reading this, please chime in with your opinion.

**Comment by apemanzilla** [comment]
Maybe the less-used ones (i.e. everything except name, vendor, the other basic info) could be instead moved to a trait + impl, `FullDeviceInfo`? This way users can easily access the complete set of information (`use ocl::Device::FullDeviceInfo`), while not overwhelming those who only need the basics.

**Comment by c0gent** [comment]
I kind of like that idea. I'd welcome PRs, even only partial implementations, of any ideas anyone has :)

**Comment by apemanzilla** [comment]
I'm relatively new to Rust, but I'll work on a PR some time this week.

**Comment by c0gent** [comment]
Great :)

**Comment by apemanzilla** [comment]
For this issue, I've hit a couple roadblocks. The first is that the sheer number of methods that need to be implemented is overwhelming - especially for `Device`. I'm considering using macros, but I'm not sure how much it will help, and I'm not familiar with them.

The second issue is that there's no way to represent the type of a variant of an enum, so I can't simply do something like `fn vendor(&self) -> Result<DeviceInfoResult::Vendor>` - I need to unwrap it to `fn vendor(&self) -> Result<String>`. This isn't a huge deal, but it does feel mildly redundant.

**Comment by c0gent** [comment]
I envisioned the removal of `*InfoResult` altogether where each function/method call would simply return the inner value directly. The biggest problem with that is, as you noticed, the sheer amount of additional code required which mostly needs to be all hand written.
