### ISSUE TITLE
Unexported internal types leak into public API of ocl

### ISSUE THREAD

**Issue by hlavaatch** [cogciprocate/ocl#108]
ocl::Platform::info() and others are returning OclCoreResult that contains **ocl_core::error::Error** which is not reexported out on the ocl and thus inaccessible from the outside.

For example trying to implement error handling for ocl::Platform::info() using the From trait compiler is complaining about
```
the trait `std::convert::From<ocl::<unnamed>::Error>` is not implemented
```
Note the **unnamed** which is in reality ocl_core::error::Error that has not been properly reexported or wrapped in a public type.
I would go as far as call this a defective public API!

As a workaround, one needs to specify additional dependency on ocl-core crate to get at the type and be able to handle it, but I think that may be different version than what the ocl crate has in its dependencies, its a mess...

**Comment by c0gent** [comment]
Yes I recently added the new ocl::Error type and there are still a few things I need to clean up. Thanks for pointing this out. I'll spend some time on it this week.

**Comment by c0gent** [comment]
8d8a4ee74f30487ad3e9ca444a87158350f93c2f should address everything. Please let me know if you find anything else. Thanks.

**Comment by c0gent** [comment]
Also, just an FYI, if in the future you need to access anything within the ocl-core crate, just `use ocl::core::...`;
