### ISSUE TITLE
Custom device info queries

### ISSUE THREAD

**Issue by Limeth** [cogciprocate/ocl#112]
As far as I can tell, it is possible to issue custom queries when a device has a certain extension, see the following: https://stackoverflow.com/questions/10852696/opencl-device-uniqueness
Would something like this be currently possible in ocl?

**Comment by c0gent** [comment]
It would certainly be possible. You'd simply need to add the proper enum variants to [DeviceInfo](https://github.com/cogciprocate/ocl/blob/master/ocl-core/src/lib.rs#L816) and the extension definitions somewhere in [cl-sys](https://github.com/cogciprocate/ocl/tree/master/cl-sys/src).

**Comment by apemanzilla** [comment]
Is there an "official" way to do this without modifying the source for the library? Having a `rawInfo(n: u32)` method to get the bytes for a given parameter would be useful, albeit not very type-safe.

**Comment by c0gent** [comment]
There is no official way but I'd be open to any good solution, including exposing the functionality via an `unsafe` method, etc.

**Comment by apemanzilla** [comment]
I'll try out a couple ideas, it would complement #104 pretty well IMO.

**Comment by c0gent** [comment]
#115 should satisfy this well enough for now. If anyone wants to do something more elaborate in the future, please open a new issue.
