### ISSUE TITLE
Issue with buffer ownership in new ocl API

### ISSUE THREAD

**Issue by TyOverby** [cogciprocate/ocl#121]
I'm trying to upgrade `ocl` from `0.17.0` to `0.19.0`, and due to the API changes to Kernel and Kernel builder, I'm either going to have to completely re-architect my project or stay at `0.17.0` for the foreseeable future.

The problem is that I used to be able to build kernels iteratively without worrying about the lifetimes of the buffers that were coming in to the kernel.  However, now with the api for setting arguments in KernelBuilder

```
pub fn arg<'s, T, A>(&'s mut self, arg: A) -> &'s mut KernelBuilder<'b> where
    T: OclPrm,
    A: Into<ArgValConverter<'b, T>>, 
```
you bind the lifetime of the buffer to the lifetime of the `KernelBuilder` (`'b` in this method signature).

This clearly doesn't matter for runtime safety because a built `Kernel` has no associated lifetime.  In fact, `Kernel` has an API that is much more permissive, allowing buffers of any lifetime (`'a` in this signature).

```
pub fn set_arg<'a, T, Ai, Av>(&self, idx: Ai, arg: Av) -> OclResult<()> where
    T: OclPrm,
    Ai: Into<ArgIdxSpecifier>,
    Av: Into<ArgValConverter<'a, T>>, 
```

"Why not just use the `Kernel` methods then?" one might ask.  I would like to do just this, but unfortunately it's impossible to get a `Kernel` instance without previously having provided those buffers to a `KernelBuilder` in the first place (otherwise you get a `BuilderWrongArgCount` error).

Resolutions: 
1. Remove the lifetime parameter from `KernelBuilder` and have arguments to the `arg` functions clone their contents.
2. Add a `build_unfinished()` method to `KernelBuilder` that doesn't perform the argcount check.

**Comment by TyOverby** [comment]
I'm going to fork ocl and attempt resolution-2.  If it works out, I'll send a PR.

**Comment by TyOverby** [comment]
I've got a fix in https://github.com/cogciprocate/ocl/pull/122

**Comment by TyOverby** [comment]
I also wrote https://github.com/cogciprocate/ocl/pull/123 which allows for String parameters (useful for when you have auto-generated argument names)

**Comment by c0gent** [comment]
@TyOverby, bf9604a3548d377b403573984b8796ccc602e234 now allows passage of owned (/cloned) `Buffer`s to `KernelBuilder`. This prevents lifetime entanglements and will allow you to pass `KernelBuilder` around where you might have used `Kernel` before.

There's also one other possible solution that I neglected to suggest (and I'm not sure if you are aware of). You can pass `None` when setting kernel buffer arguments. This allows you to then set them later (after building a kernel, for example). A caveat is that this may cause segfaults if you aren't careful about ensuring they are set before enqueuing the kernel. (The ability to pass `None` as an arg falls into the category of unsafe-but-marked-safe behaviour that I eventually want to try to eliminate but that's another story.)

Please let me know if either of these two solutions handle your problem and whether or not you still think we should move forward with #122 or if there's anything else you think of.

**Comment by c0gent** [comment]
@TyOverby I'm curious to know how things are going (passing owned buffers instead of references when creating a kernel) and whether or not you think this issue still needs more attention.

Please re-open if it does. I'll also close #122 for now.
