### ISSUE TITLE
CL_INVALID_KERNEL_ARGS (-52)   while using arg_local()

### ISSUE THREAD

**Issue by davenza** [cogciprocate/ocl#124]
Hi, I'm trying to use a kernel with local buffers. I used the KernelBuilder::arg_local function to assign the local buffer, but it returns CL_INVALID_KERNEL_ARGS (-52) .

This is a minimum working example:

```rust
extern crate ocl;

use ocl::ProQue;

fn main() {
    local_arg().unwrap();
}

fn local_arg() -> ocl::Result<()> {
    let src = r#"
        __kernel void local_args(__local double* localVec) {

        }
    "#;

    let pro_que = ProQue::builder()
        .src(src)
        .build()?;

    let kernel_diff = pro_que.kernel_builder("local_args")
        .global_work_size(1)
        .arg_local::<f64>(64)
        .build()?;
    
    unsafe { kernel_diff.enq()?; }
    Ok(())
}
```
Which gives the following error when executed:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 

################################ OPENCL ERROR ############################### 

Error executing function: clEnqueueNDRangeKernel("local_args")  

Status error code: CL_INVALID_KERNEL_ARGS (-52)  

Please visit the following url for more information: 

https://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml/clEnqueueNDRangeKernel.html#errors  

############################################################################# 
', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

What I am doing wrong here? The crate is incredibly easy to use, but I couldn't address this issue.

EDIT: If it helps, the error is triggered when executing the line:
```rust
unsafe { kernel_diff.enq()?; }
```

**Comment by c0gent** [comment]
I'm glad you caught this. It looks like a recent change (#114) broke the ability to set kernel arguments and embarrassingly there were no tests which actually set one. I'll add a test to ensure this never happens again.

Please try using the latest version of `ocl` on master by changing the import line in your `Cargo.toml` as follows:

```
ocl = { git = "https://github.com/cogciprocate/ocl.git" } 
```

If that works for you I'll publish the changes to crates.io. Thanks!

**Comment by davenza** [comment]
@c0gent Thanks for your quick response and this incredible crate. It works perfectly for me now.

**Comment by c0gent** [comment]
`0.19.1` has been published to crates.io. Thanks again and glad you enjoy the crate :)
