### ISSUE TITLE
OpenCL interop version mismatch

### ISSUE THREAD

**Issue by 64** [cogciprocate/ocl#125]
Looks like the current version of `ocl_interop` on crates.io hasn't been updated in a while. It still depends on `ocl 0.16.0` and gives a type mismatch when you try to use it with `ocl 0.19.0`:

```
error[E0308]: mismatched types
  --> src/frame.rs:29:33
   |
29 |         let ctx: ocl::Context = ocl_interop::get_context().unwrap();
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `ocl::Context`, found struct `ocl::standard::context::Context`
   |
   = note: expected type `ocl::Context`
              found type `ocl::standard::context::Context`
note: Perhaps two different versions of crate `ocl` are being used?
  --> src/frame.rs:29:33
   |
29 |         let ctx: ocl::Context = ocl_interop::get_context().unwrap();
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0308`.
```

**Comment by c0gent** [comment]
I've forgotten about `ocl_interop` lately. I need to create a test for it or something to make sure it stays up to date...

Please feel free to submit a PR to update or else I'll take care of it tomorrow. I'm away from my computer for the day.

Thanks :)

**Comment by 64** [comment]
I think the `Cargo.toml` is actually correct, but it just needs to be published.

**Comment by c0gent** [comment]
I see.

**Comment by c0gent** [comment]
Do you happen to have SDL and GLFW installed? If so could you please try running the `ocl-interop` tests? I'm having all sorts of driver issues with OpenGL right now.

```
git clone https://github.com/cogciprocate/ocl.git
cd ocl/ocl-interop
cargo test
```

If that works I'll publish `0.2.0`.

**Comment by 64** [comment]
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.57s
     Running /tmp/ocl/target/debug/deps/ocl_interop-bb7f66ec97221dd7
running 1 test
test tests::it_doesnt_crash ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
     Running /tmp/ocl/target/debug/deps/lib-88fcb84903026332
running 1 test
error: Not implemented
error: test failed, to rerun pass '--test lib'
```

Does compile though. I'll hunt down where that error message is coming from and get back to you.

**Comment by 64** [comment]
Looks like it's caused by this line:

    let cl_buff =
        ocl::Buffer::<f32>::from_gl_buffer(ocl_pq.queue(), None, self.gl_buff).unwrap();

https://github.com/cogciprocate/ocl/blob/master/ocl/src/standard/buffer.rs#L1740

Could also be a driver issue. I remember trying to get some non-rust examples of interop to work, but they were all giving me the same error (`CL_MEM_OBJECT_ALLOCATION_FAILURE` on `clCreateFromGlTexture`).

**Comment by c0gent** [comment]
Ok well I'll mess with this on my laptop later if you can't get it to work. It's a pain to get everything set up properly to get these tests to run so thanks for trying.

**Comment by 64** [comment]
Yep it's a driver issue on my end: https://github.com/intel/beignet/issues/5

I'll try and fiddle a bit more.

**Comment by c0gent** [comment]
Looks like we can't totally solve your problem but [ocl-interop 0.1.5](https://crates.io/crates/ocl-interop) is published.
