### ISSUE TITLE
CL_INVALID_ARG_VALUE (-50) while using arg_named with None

### ISSUE THREAD

**Issue by EpicatSupercell** [cogciprocate/ocl#126]
While creating a kernel (unmodified example code):

```rust
let kernel = Kernel::builder()
    .program(&program)
    .name("rgbmix")
    .queue(queue)
    .global_work_size((self.width, self.height))
    .arg_named("input", None::<&Image<u8>>)
    .arg_named("output", None::<&Image<f32>>)
    .build()?;
```

the command of build() will crash with a CL_INVALID_ARG_VALUE (-50) error.
The issue is that it calls to `clSetKernelArg` with the value extracted out of `None`.

Commit #114 fixes it but conflicts with arg_local (see #124), so it was reverted.

Tested on ocl 0.19.1, Nvidia GPU with proprietary drivers on linux.

**Comment by c0gent** [comment]
Ok so it looks like if we skip setting the arg to `null` explicitly for all `mem` args which are `None` it should make all of the platforms happy. I might not have time to make this change and properly test it right away so feel free to put in a pull request for it.

**Comment by alexkirsz** [comment]
@c0gent Would it be possible to cut a new release of ocl with the fix in? I can confirm that it works for me 😄

**Comment by c0gent** [comment]
Certainly. I'll merge a few more changes then put one out.

**Comment by c0gent** [comment]
@alexkirsz: 0.19.3 finally published :)
