### ISSUE TITLE
Float arguments not passed to kernel

### ISSUE THREAD

**Issue by CasperN** [cogciprocate/ocl#127]
Hi, I may be misusing your crate or OCL since I'm new but the following failure is unexpected

```
#[test]
    fn ocl_float_add() {
        let src = r#"__kernel void f(float a, float b, __global float *c) {*c = a + b;}"#;
        let pq = ProQue::builder().src(src).dims(1).build().unwrap();
        let c = pq.buffer_builder().build().unwrap();
        let k = pq.kernel_builder("f").arg(3.14).arg(2.71).arg(c.clone()).build().unwrap();
        unsafe { k.enq().unwrap() };
        let mut v = vec![0f32; 1];
        c.read(&mut v).enq().unwrap();
        assert_eq!(v[0], 5.85);
    }
```

It seems `arg` does not pass constants by value and instead gibberish is passed to the OCL function. If this is intended behavior think this example should not compile or at least there should be a warning in the docs for future newbies.

**Comment by CasperN** [comment]
It seems making the argument types explicit, `3.14f32` and `2.72f32`, makes this work within floating point error. I guess there was some incorrect type inference causing the initial version to yield gibberish.

I'll leave this issue open since its kind of a subtle bug and there may be way to make it an error for the future.

**Comment by c0gent** [comment]
Ok thanks. I'll definitely take a look at this. Let me know if you discover anything else about it.

**Comment by c0gent** [comment]
Those values must have been interpreted as f64 then, right?

**Comment by CasperN** [comment]
Yep, they were defaulted to doubles.

**Comment by c0gent** [comment]
Well there is a type checking system but it is inactive on platforms that don't provide kernel arg info (which I'm guessing is the case for you). There is an arg size check done by the runtime though. I'm not sure why that didn't give you a `CL_INVALID_ARG_SIZE` error.

Out of curiosity, what happens when you pass a literal reference i.e. `.arg(&3.14)`?

**Comment by CasperN** [comment]
That fails too regardless if I change the kernel to expect `float *` or `float`.

**Comment by c0gent** [comment]
I've added a test to ensure that this fails with an error: b11fa933821245e2d1e75a32e0bede78e2143f7a.

If, as I suspect, that test fails on your platform, there is probably nothing we can do about it.

Please re-open if needed.
