### ISSUE TITLE
Failed buffer size assertion on Beignet

### ISSUE THREAD

**Issue by dmarcuse** [cogciprocate/ocl#128]
When using the Beignet OpenCL implementation, `CL_MEM_SIZE` seems to be not equal to the buffer length, but the next multiple of 4 greater than or equal to the buffer length.

<details><summary>Minimal example code</summary><p>

```rust
extern crate ocl;

use ocl::{Device, Platform, Context};
use ocl::{Result as OclResult};
use ocl::flags::DeviceType;
use ocl::builders::BufferBuilder;
use ocl::enums::MemInfo;

fn main() -> OclResult<()> {
	for p in Platform::list() {
		for d in Device::list(p, Some(DeviceType::ALL))? {
			println!("Testing device {} on platform {} (version {})", d.name()?, p.name()?, p.version()?);
			let context = Context::builder().platform(p).devices(d).build()?;
			let buffer = BufferBuilder::<u8>::new().context(&context).len(10).build()?;
			println!("Buffer size: {}", buffer.mem_info(MemInfo::Size)?);
		}
	}

	Ok(())
}
```

</p></details>

Running the above example code results in a panic in debug mode, and shows the differing `CL_MEM_SIZE` values in release mode:

<details><summary>Output</summary><p>

Debug mode:
```
Testing device Intel(R) HD Graphics Kabylake ULT GT2 on platform Intel Gen OCL Driver (version OpenCL 2.0 beignet 1.4 (git-fc5f430c))
thread 'main' panicked at 'assertion failed: {
    let l_r =
        match core::get_mem_object_info(&obj_core, MemInfo::Size)? {
            MemInfoResult::Size(len_bytes) =>
            len_bytes / ::std::mem::size_of::<T>(),
            _ => unreachable!(),
        };
    l_r == len
}', /home/dominic/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.19.1/src/standard/buffer.rs:1708:9
```

Release mode:
```
Testing device Intel(R) HD Graphics Kabylake ULT GT2 on platform Intel Gen OCL Driver (version OpenCL 2.0 beignet 1.4 (git-fc5f430c))
Buffer size: 12
Testing device Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz on platform Intel(R) OpenCL (version OpenCL 1.2 LINUX)
Buffer size: 10
```

</p></details>

---

Usually I would dismiss this as an issue with Beignet, but after looking at [the clGetMemObjectInfo specification](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/clGetMemObjectInfo.html), I'm not so sure: The specification says that `CL_MEM_SIZE` represents "the _actual_ size of the data store associated with memobj in bytes", which implies it may not be the same as the length specified when creating the memory object. Because of this, I think that the [failing assertion](https://github.com/cogciprocate/ocl/blob/a065ca380dca6f757ea0ab8bc93979ef93e34b7e/ocl/src/standard/buffer.rs#L1708-L1714) should simply be removed.

**Comment by c0gent** [comment]
Good point. It should actually be `>=` not `==` but I agree, I'll just remove it.

Thanks!

**Comment by c0gent** [comment]
I went ahead and just changed it to `>=` in 667e33f. Give that a try and let me know.

**Comment by dmarcuse** [comment]
It now runs properly in both debug and release mode. To play devil's advocate, there could be some OpenCL implementation using compressed memory to return a size smaller than the virtual buffer length, but I think `>=` is fine for now.
