### ISSUE TITLE
Kernel compilation hangs on AMD

### ISSUE THREAD

**Issue by webmaster128** [cogciprocate/ocl#129]
I have a host program that lools like this in a GPU thread:

```rust
        let mut program_builder = ProgramBuilder::new();
        program_builder
            .src(include_str!("opencl/types.cl"))
            .src(include_str!("opencl/curve25519-constants.cl"))
            .src(include_str!("opencl/curve25519-constants2.cl"))
            .src(include_str!("opencl/curve25519.cl"))
            .src(include_str!("opencl/sha2.cl"))
            .src(include_str!("opencl/sha256.cl"))
            .src(include_str!("opencl/sha512.cl"))
            .src(include_str!("opencl/bip39.cl"))
            .src(include_str!("opencl/entry.cl"));

        let platforms = Platform::list();
        if platforms.len() == 0 {
            return Err("No OpenCL platforms exist (check your drivers and OpenCL setup)".into());
        }
        if platform_idx >= platforms.len() {
            return Err(format!(
                "Platform index {} too large (max {})",
                platform_idx,
                platforms.len() - 1
            ).into());
        }

        let platform = platforms[platform_idx];
        eprintln!("GPU platform {} {}", platform.vendor()?, platform.name()?);

        let device = Device::by_idx_wrap(platform, device_idx).expect("Requested device not found");
        eprintln!("Using GPU device {} {}, OpenCL {}", device.vendor()?, device.name()?, device.version()?);
        eprintln!("MaxWorkGroupSize {}", device.info(DeviceInfo::MaxWorkGroupSize)?);

        let context = Context::builder()
            .platform(platform)
            .devices(device.clone())
            .build()?;
        eprintln!("GPU context created.");

        let queue = Queue::new(&context, device, None)?;
        eprintln!("GPU queue created.");

        let program = program_builder
            .devices(device)
            .build(&context)?;
        eprintln!("GPU program successfully compiled.");
```

On a NVIDIA card (Ubuntu 18.04) and a Intel CPU (Macbook) this works fine. But on a AMD card, this hangs between "GPU queue created." and "GPU program successfully compiled.". Unfortunatly I do not get an error message this time, nor any kind of progress.

```
GPU platform Advanced Micro Devices, Inc. AMD Accelerated Parallel Processing
Using GPU device Advanced Micro Devices, Inc. gfx900, OpenCL 1.2
MaxWorkGroupSize 256
GPU context created.
GPU queue created.
```

It hangs there for minutes where other platforms need a second or two to compile. Any idea what could be happening here? I'm on

```
rustc 1.32.0-nightly (21f268495 2018-12-02)
ocl 0.19.1
Ubuntu 18.04
```

**Comment by c0gent** [comment]
Hard to say. I'd first try removing parts of the source code (comment out `.src(...)` lines) and see if you can narrow it down a bit.

**Comment by c0gent** [comment]
I'm not sure exactly why compilation is hanging but all I meant was that it would probably be a good idea to minimize the problem and try to determine which code is causing the problem by removing portions of it until it stops hanging (or adding it slowly).

I don't think there are any interfaces to see what the compiler is doing since it's all proprietary. There may be some AMD extensions for it which you'd have to access directly (via FFI calls, etc.).

For now though, see if you can narrow it down. At the very least you can put together a bug report for AMD.

**Comment by dmarcuse** [comment]
>I don't think there are any interfaces to see what the compiler is doing since it's all proprietary.

You should be able to start compilation asynchronously and use [`clGetProgramBuildInfo`](https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/clGetProgramBuildInfo.html) to get basic information. I haven't tried it before, but if it's updated as the build progresses, maybe `CL_PROGRAM_BUILD_LOG` would yield some insights?

**Comment by c0gent** [comment]
Yes I've never tried that either. It's worth a shot.

**Comment by webmaster128** [comment]
Thanks for the help! Looks like ocl-core provides all the methods I need to build and check in two different threads:

```rust
        let strings = program_builder.get_src_strings().unwrap();
        let program = core::create_program_with_source(&context, &strings)
            .expect("Error creating source");
        let cmplr_opts = CString::new("").unwrap();

        let program_ref = &program;
        thread::spawn(move || loop {
            // check build status
            let status = core::get_program_build_info(
                program_ref, device, core::ProgramBuildInfo::BuildStatus
                ).expect("error");
            let log = core::get_program_build_info(
                program_ref, device, core::ProgramBuildInfo::BuildLog
                ).expect("error");
            eprintln!("Status: {}; Log: {}", status, log);
            thread::sleep(Duration::from_millis(1000));
        });

        eprintln!("Build started");
        core::build_program(
            &program, Option::Some(&[device]),
            &cmplr_opts, None, None)
            .expect("Could not build");
        eprintln!("Build ended");
```

Now my only problem is how do I get a reference to `program` into two different threads? The above code does not compile because of

```
error[E0597]: `program` does not live long enough
   --> src/gpu.rs:96:28
    |
96  |         let program_ref = &program;
    |                            ^^^^^^^ borrowed value does not live long enough
...
153 |     }
    |     - borrowed value only lives until here
    |
    = note: borrowed value must be valid for the static lifetime...
```

Any rust pro here?

**Comment by webmaster128** [comment]
Thanks @dmarcuse for the great explanation. Build status observer is running now. The status I cannot observe because of #130 but it is probably -3, CL_BUILD_IN_PROGRESS. The log is empty all the time.

@c0gent I also followed your suggestion to comment out code. It turns out that all the dependency files compile and only when I add the kernel the compilation hangs. But with all this inline code I guess the code starts making trouble when it is used only. Looks like I need to clear my kernel and add the code back line by line.

**Comment by webmaster128** [comment]
Is there any known code size / kernel size limitation I need to consider? It looks like compilation hangs as soon as I exceed a certain code amount and I can comment out multiple different function that all work in their own but not together.

**Comment by dmarcuse** [comment]
I'm not aware of any specific limits, but I have experienced cases where excessive loop unrolling and (implicit) function inlining caused compilation to fail or take several minutes to complete, on both AMD and Intel.

**Comment by webmaster128** [comment]
Created a post in the AMD forum now (https://community.amd.com/message/2890520). Thanks for all your support!

Closing as out of scope
