### ISSUE TITLE
Hash impl for OpenCL objects

### ISSUE THREAD

**Issue by dmarcuse** [cogciprocate/ocl#136]
It would be convenient if OpenCL objects had an implementation for `Hash`, to support uses like `HashSet<Device>`. It should be pretty trivial to implement, just writing the pointer of the object to the `Hasher`.

**Comment by c0gent** [comment]
Sounds good to me.

**Comment by dmarcuse** [comment]
Should I implement this in a PR?

**Comment by c0gent** [comment]
Sure if you'd like. 

I'd probably just start by implementing it for [`DeviceId`](https://github.com/cogciprocate/ocl/blob/master/ocl-core/src/types/abs.rs#L401) (and `PlatformId`, etc. if you want). Then you can just derive it on the higher level types.
