### ISSUE TITLE
Windows ABI

### ISSUE THREAD

**Issue by pravic** [cogciprocate/ocl#14]
Intel OpenCL SDK provides headers with the `stdcall` calling convention under Windows. Your bindings uses `extern "C"` [unconditionally](https://github.com/cogciprocate/ocl/blob/master/src/cl_h.rs#L579), though.

```
#if defined(_WIN32)
    #define CL_API_ENTRY
    #define CL_API_CALL     __stdcall
    #define CL_CALLBACK     __stdcall
...
/* Platform API */
extern CL_API_ENTRY cl_int CL_API_CALL
clGetPlatformIDs(cl_uint          /* num_entries */,
                 cl_platform_id * /* platforms */,
                 cl_uint *        /* num_platforms */) CL_API_SUFFIX__VERSION_1_0;
```

**Comment by c0gent** [comment]
I've only just begun to add windows support and I'm afraid I'm not completely familiar with the differences in calling conventions. I'll study up on this. I'd appreciate any help you could provide.

**Comment by pravic** [comment]
From "[The Book](http://doc.rust-lang.org/nightly/book/ffi.html)", FFI chapter:

> Most of the abis in this list are self-explanatory, but the `system` abi may seem a little odd. This constraint selects whatever the appropriate ABI is for interoperating with the target's libraries. For example, on **win32** with a x86 architecture, this means that the abi used would be `stdcall`. On x86_64, however, windows uses the `C` calling convention, so `C` would be used. This means that in our previous example, we could have used `extern "system" { ... }` to define a block for all windows systems, not only x86 ones.

In general, most of windows libraries uses the `stdcall` convention (but it depends, need to verify always). So, if windows uses `stdcall` and linux uses `C`, you can choose the `extern "system"` once to write the portable Rust bindings.

**Comment by c0gent** [comment]
Done: 120eeb180c29fe685e0ebdabaeaf590859ce6158

Thanks for your feedback, keep it coming.
