### ISSUE TITLE
impl std::error::Error for ocl::error::Error

### ISSUE THREAD

**Issue by remexre** [cogciprocate/ocl#140]

**Comment by c0gent** [comment]
Unfortunately this interferes with the use of [`failure`](https://github.com/rust-lang-nursery/failure) for Errors. You should be able to do [`ocl_error.compat()`](https://docs.rs/failure/0.1.5/failure/trait.Fail.html#method.compat) to convert it to something that does.

**Comment by remexre** [comment]
I was under the impression that if you impl'd Error instead of Fail, the blanket implementation of Fail would kick in; that way, people who use `Result<T, Box<dyn Error + Sync>>` or similar don't have to call `.compat()` on everything, while people who use failure have the same error handling story.

**Comment by c0gent** [comment]
Yeah you're probably right. I'll take a closer look at some point.
