### ISSUE TITLE
Colorify under Windows

### ISSUE THREAD

**Issue by pravic** [cogciprocate/ocl#15]
… is not works, of course:

> Looping through avaliable platforms (3):
←[34mPlatform { Profile: FULL_PROFILE ,

It would be better do not use terminal colors in examples. Or patch colorify for Windows support, idk.

**Comment by c0gent** [comment]
Agreed. I'll sort that out.

**Comment by c0gent** [comment]
74ccc221cf02e6ac89fbb6b242d13963aa4930ac

**Comment by pravic** [comment]
ocl depends from colorify 0.1 still.

**Comment by c0gent** [comment]
Heh, whoops.

79f4f5775db02e30dcc2beaf898dfe0d61b8793f
