### ISSUE TITLE
Queue should block / finish when it is dropped. 

### ISSUE THREAD

**Issue by charles-r-earp** [cogciprocate/ocl#155]
I just troubleshooted a bug where kernels would not be executed, presumably because the queue was destroyed immediately after construction -> kernel.cmd().queue().enq().unwrap() -> return. The fix was to call Queue.finish(). It seems like a good idea to have this be default behavior on drop. Unless there is a way to provide a warning. It created an unexpected and very difficult to diagnose bug, which seems to be due to a race condition.

**Comment by c0gent** [comment]
Interesting. Could you provide a simplified example of the failure case and some details about your environment/platform?

**Comment by charles-r-earp** [comment]
fn main() {
  let src = r#"kernel void func(global float* out) {
    out[get_global_id(0)] = 1;
  }"#;
  let context = ocl::Context::builder()
    .build()
    .unwrap();
  let program = ocl::Program::builder()
    .src(src)
    .build(&context)
    .unwrap();
  let mut x = vec![0f32; 10];
  let xbuf = ocl::Buffer::builder()
    .context(&context)
    .len(x.len())
    .build()
    .unwrap();
  let kernel = ocl::Kernel::builder()
    .program(&program)
    .name("func")
    .global_work_size([x.len()])
    .arg(&xbuf)
    .build()
    .unwrap();
  let queue1 = ocl::Queue::new(&context, context.get_device_by_wrapping_index(0), None)
    .unwrap();
  unsafe { kernel.cmd().queue(&queue1).enq().unwrap(); }
  let queue2 = ocl::Queue::new(&context, context.get_device_by_wrapping_index(0), None)
    .unwrap();
  xbuf.read(&mut x).queue(&queue2).enq().unwrap();
  println!("{:?}", &x); // garbage with queue2, works with queue1
}

/** I figured out that the issue was that I was creating a new queue for the read command. The result is that x comes back as uninitialized. Is it necessary to use the same queue per buffer? **/

**Comment by c0gent** [comment]
I'm guessing that somehow the buffer read is happening before the kernel executes. Since you're using blocking calls this is definitely not supposed to happen.

I can't reproduce (and may not be able to fix). Would you mind pasting your `clinfo` or `cargo run --example info_core` output?

P.S. Wrap code and terminal output in triple backticks: ` ``` ` (or single backtick for inline code)

**Comment by charles-r-earp** [comment]
clinfo
Number of platforms                               1
  Platform Name                                   Portable Computing Language
  Platform Vendor                                 The pocl project
  Platform Version                                OpenCL 1.2 pocl 1.1 None+Asserts, LLVM 6.0.0, SPIR, SLEEF, DISTRO, POCL_DEBUG
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             POCL

  Platform Name                                   Portable Computing Language
Number of devices                                 1
  Device Name                                     pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Device Vendor                                   GenuineIntel
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 1.2 pocl HSTR: pthread-x86_64-pc-linux-gnu-skylake
  Driver Version                                  1.1
  Device OpenCL C Version                         OpenCL C 1.2 pocl
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               12
  Max clock frequency                             4100MHz
  Device Partition                                (core)
    Max number of sub-devices                     12
    Supported partition types                     equally, by counts
  Max work item dimensions                        3
  Max work item sizes                             4096x4096x4096
  Max work group size                             4096
  Preferred work group size multiple              8
  Preferred / native vector sizes                 
    char                                                16 / 16      
    short                                               16 / 16      
    int                                                  8 / 8       
    long                                                 4 / 4       
    half                                                 0 / 0        (n/a)
    float                                                8 / 8       
    double                                               4 / 4        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  Yes
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
  Address bits                                    64, Little-Endian
  Global memory size                              14359248896 (13.37GiB)
  Error Correction support                        No
  Max memory allocation                           4294967296 (4GiB)
  Unified memory for Host and Device              Yes
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        Read/Write
  Global Memory cache size                        9437184 (9MiB)
  Global Memory cache line size                   64 bytes
  Image support                                   Yes
    Max number of samplers per kernel             16
    Max size for 1D images from buffer            268435456 pixels
    Max 1D or 2D image array size                 2048 images
    Max 2D image size                             16384x16384 pixels
    Max 3D image size                             2048x2048x2048 pixels
    Max number of read image args                 128
    Max number of write image args                128
  Local memory type                               Global
  Local memory size                               8388608 (8MiB)
  Max number of constant args                     8
  Max constant buffer size                        8388608 (8MiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      1ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            Yes
    SPIR versions                                 1.2
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                
  Device Extensions                               cl_khr_byte_addressable_store cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_3d_image_writes cl_khr_spir cl_khr_fp64 cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Portable Computing Language
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [POCL]
  clCreateContext(NULL, ...) [default]            Success [POCL]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Portable Computing Language
    Device Name                                   pthread-Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.11
  ICD loader Profile                              OpenCL 2.1

**Comment by c0gent** [comment]
I figured it was POCL. 

Probably just use one queue for everything (no need to use more than one with sync code anyway). Not sure what I can do on this end but let me know if you have any ideas. BTW, this has nothing to do with the queue dropping, it's just some weirdness in how POCL queues stuff.

**Comment by charles-r-earp** [comment]
Interesting. Thanks.
