### ISSUE TITLE
Making the `WriteSrc` trait public

### ISSUE THREAD

**Issue by Patryk27** [cogciprocate/ocl#158]
Hello :-)

I have a case where I need to create a few OpenCL buffers with different default *non-constant* values (e.g. each buffer must be filled with random numbers generated on the host during bootstrapping).

I've tried to create a generic function that I could use to initialize those buffers in just a few lines (for convenience), but I've encountered a trouble - namely: the `WriteSrc` trait is private, which makes it impossible to create function such as this:

```rust
fn create_and_fill_buffer<T>(
    name: &str,
    queue: &ProQue,
    map: impl FnMut() -> T,
) -> Buffer<T>
  where T: OclPrm,
        Vec<T>: Into<WriteSrc<'_, T>> { // <- here's the bound that *must* be imposed (because of `device.write(...)` invocation), but - sadly - cannot be
    let buf_device = queue.create_buffer()
        .expect(&format!("failed to create the [{}] buffer - insufficient GPU memory?", name));

    let buf_host: Vec<_> = (0..buf_device.len())
        .into_iter()
        .map(|_| map())
        .collect();

    buf_device.write(&buf_host)
        .enq()
        .expect(&format!("failed to fill the [{}] buffer - insufficient GPU memory?", name));

    buf_device
}
```

Example use case, FWIW:
```rust
fn create_velocities_buffer(queue: &ProQue) -> Buffer<Float2> {
    create_and_initialize_buffer("velocities", queue, || {
        Float2::new(
            -0.5 + random::<f32>(),
            -0.5 + random::<f32>(),
        )
    })
}
```

For now I've gone with a macro, but it would be really helpful if the `WriteSrc` trait was made public[1] - what do you think?

[1] unless there's some other way to do that, in which case I'd be glad to learn it

Thank you very much,
Patryk.

**Comment by c0gent** [comment]
This compiles fine for me (without the `Vec<T>: Into<WriteSrc<'_, T>>` part):

```rust
fn create_and_fill_buffer<T>(
    name: &str,
    queue: &ProQue,
    mut map: impl FnMut() -> T,
) -> Buffer<T>
  where T: OclPrm,
{
    let buf_device = queue.create_buffer()
        .expect(&format!("failed to create the [{}] buffer - insufficient GPU memory?", name));

    let buf_host: Vec<_> = (0..buf_device.len())
        .into_iter()
        .map(|_| map())
        .collect();

    buf_device.write(&buf_host)
        .enq()
        .expect(&format!("failed to fill the [{}] buffer - insufficient GPU memory?", name));

    buf_device
}
```

Is there another usage example which won't work with the above function?

I'm happy to make the `WriteSrc` *enum* public either way.

**Comment by Patryk27** [comment]
Hm, you are right - it compiles just fine; I use nightly version of Rust, so I guess it must have been some strange nightly-nightly regression.

Thanks - I guess nothing needs to be changed here :-)

**Comment by c0gent** [comment]
Interesting. Glad you got to the bottom of it!
