### ISSUE TITLE
Changing work-size without re-compiling

### ISSUE THREAD

**Issue by calebwin** [cogciprocate/ocl#166]
Can I change the work size of a `Kernel` without having to re-compile it? Is that what the `default_work_size` functions do?

**Comment by nsrip** [comment]
Yes, you can change the work size without re-compiling. You can either use the `set_default_*_work_size` methods for `Kernel`, or you can set the work size for a single command like this:

```rust
kernel.cmd()
    .global_work_size(...)
    .local_work_size(...)
    .enq()?
```

See the [`KernelCmd`](https://docs.rs/ocl/0.19.3/ocl/builders/struct.KernelCmd.html) documentation.

**Comment by calebwin** [comment]
Cool, thanks.

Can I change arguments without re-compiling?

**Comment by calebwin** [comment]
I want to minimize re-compilation - is the only time I need to re-compile when I am using a different `Program`?

**Comment by nsrip** [comment]
Correct, a kernel comes from a program, and you only need to re-compile if you change the program (e.g. if you change the source code). You can change the value of kernel arguments as much as you want. You can even have different copies of the same kernel with different argument vales, without re-compiling.

I'd recommend reading the OpenCL specification for whichever version of OpenCL you're using. They're available [here](https://www.khronos.org/registry/OpenCL/). The specifications describe the C API but the basic behavior of the different objects (Programs, Kernels, Queues, etc.) is the same in `ocl`.

**Comment by calebwin** [comment]
This is really good to know. Thank you for your time.
