### ISSUE TITLE
Remove dependency without license

### ISSUE THREAD

**Issue by michaelmattig** [cogciprocate/ocl#200]
This crate uses old versions of num and rand which in turn depend on a crate named fuchsia-cprng whose source is no longer available and no license is given on crates.io. The command `cargo license` prints 

> ...
> N/A (4): fuchsia-cprng

This PR updates the dependencies to remove this dependency. As `weak_rng` and `XOrShift` are no longer available in `rand`, I migrated to `SmallRng` instead : https://github.com/cogciprocate/ocl/pull/199

**Comment by c0gent** [comment]
Should be fixed.
