### ISSUE TITLE
error: failed to select a version for the requirement `rustc_version = "^0.1"`

### ISSUE THREAD

**Issue by xuqinghan** [cogciprocate/ocl#203]
install  https://github.com/davenza/kde_ocl 

 got error:

python setup.py install
running install
running bdist_egg
running egg_info
writing kde_ocl.egg-info/PKG-INFO
writing dependency_links to kde_ocl.egg-info/dependency_links.txt
writing requirements to kde_ocl.egg-info/requires.txt
writing top-level names to kde_ocl.egg-info/top_level.txt
reading manifest file 'kde_ocl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'kde_ocl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
    Updating crates.io index
error: failed to select a version for the requirement `rustc_version = "^0.1"`
candidate versions found which didn't match: 0.3.3, 0.3.2, 0.3.1, ...
location searched: crates.io index
required by package `ocl-core v0.11.2`
    ... which is depended on by `ocl v0.19.3`

**Comment by WaffleLapkin** [comment]
This is related to the yank of `0.1.*` crate versions of [`rustc_version`](https://docs.rs/rustc_version/0.3.3/rustc_version/). This can be fixed by updating deps, like in [this PR](https://github.com/DanielKeep/cargo-script/pull/80).
