### ISSUE TITLE
The test program on Ubuntu 21.10 may not be using the GPU

### ISSUE THREAD

**Issue by ben-cottrell-nz** [cogciprocate/ocl#207]
I've tried to build and execute `trivial.rs`, and it appears to work, although I get messages from the output about a possibly wrong ICD:
```
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
The value at index [200007] is now '10'!
```

My GPU model is NVIDIA GeForce GT 1030. I have driver version 510 installed, and have installed the latest packages for ocl-icd-libopencl1, and nvidia-opencl-dev. Is there anything else I need to install?

**Comment by c0gent** [comment]
Sorry for the delay responding. Troubleshooting your issue is beyond the scope of this project. Hopefully you've fixed it by now :)
