### ISSUE TITLE
Why not using travis (or another) ?

### ISSUE THREAD

**Issue by Kerosene2000** [cogciprocate/ocl#21]
Why not using travis to call `cargo build`, `cargo test` for each commit ?
Each pull request/commit can update the documentation...
I already use it on some of my rust libraries, so I can help you for that (I think) 😄

**Comment by c0gent** [comment]
Yes I need to set it up. Maybe I will do that this week. I'll let you know if I need any help.

**Comment by Kerosene2000** [comment]
If you want, [this document](https://github.com/kmcallister/travis-doc-upload/blob/master/README.md) really helps !

**Comment by c0gent** [comment]
Excellent, thanks.

**Comment by pravic** [comment]
@Kerosene2000, it can be useful only for the docs. Because you cannot test OpenCL in arbitrary travis machine :)

**Comment by Kerosene2000** [comment]
That's right ! I didn't think of that 😄 
You can't ask a specific machine on travis ?

**Comment by pravic** [comment]
No idea, I've never tried the travis before.

**Comment by Kerosene2000** [comment]
here is [a little help file somehow](https://github.com/luqmana/rust-opencl/blob/master/.travis.yml), I don't really know if that works 🍋

**Comment by c0gent** [comment]
After some investigation, this won't be useful enough to warrant bothering with for now considering the constraints of an OpenCL environment.

Eventually a comprehensive, cross-platform test suite will need to be set up but I'm not sure that travis will necessarily be the way to do it.

Publishing documentation has been a simple shell script for quite some time and I see no reason to change that.
