### ISSUE TITLE
The large global_id confuses me

### ISSUE THREAD

**Issue by lpcy** [cogciprocate/ocl#226]
I used code similar to this project example, and set ProQue::builder().dims(10000000000). I found Some global_id will be processed twice, some global_id was not processed. I have discovered a possible boundary point: 2147483648 (2^31). So in opencl, I print global_id:
```    
    size_t gid = get_global_id(0);
    if(gid == 2147483647 || gid == 2147483648){
        printf("gid:%ld\n",gid);
    }
```
Finally, these were printed:
  gid:2147483647
  gid:2147483647
I am not sure why this situation occurred and how to avoid it. I am using NVIDIA GeForce MX150 and Windows 10 OS.

**Comment by c0gent** [comment]
Not specific to this library but that is the maximum positive value of a 32 bit signed integer, which is the size used for kernel dimensions on your platform. Try using multiple dimensions such as: `ProQue::builder().dims((100000,100000))` and adjust your kernel accordingly. In your kernel you'd use `get_global_id(0)` to get the first and `get_global_id(1)` to get the second dimension.

Hope that helps.

**Comment by lpcy** [comment]
> Not specific to this library but that is the maximum positive value of a 32 bit signed integer, which is the size used for kernel dimensions on your platform. Try using multiple dimensions such as: `ProQue::builder().dims((100000,100000))` and adjust your kernel accordingly. In your kernel you'd use `get_global_id(0)` to get the first and `get_global_id(1)` to get the second dimension.
> 
> Hope that helps.


Thank you for your reply. Where can I obtain or calculate this value to determine the maximum support of only 32 bits?

**Comment by c0gent** [comment]
To be honest I'm not really sure. It's probably correlated with the `AddressBits` (`CL_DEVICE_ADDRESS_BITS`) parameter from `DeviceInfo` (`cl_get_device_info`) but I can't remember exactly. You can run `clinfo` or the the `info_core` example in this project (`cargo run --example info_core`) to view the `AddressBits` parameter.

**Comment by c0gent** [comment]
Let me know what yours lists.
