### ISSUE TITLE
bool isn't `OclPrm`

### ISSUE THREAD

**Issue by yongqli** [cogciprocate/ocl#30]

**Comment by c0gent** [comment]
Correct. The Rust `bool` is not the same size as a C boolean (which is just an `int`, a machine sized integer). A boolean in OpenCL C (in a kernel) is just an `int`/`uint` (doesn't matter which).

Use the `ocl::aliases::cl_bool` (which is just a `u32`) when using booleans within a buffer, etc. Cast them as you normally would (`true as ocl::aliases::cl_bool`, or just `true as u32`).

Let me know if that makes sense or if you want an example of what I mean.

**Comment by yongqli** [comment]
Hmm, I've had a bit of trouble with that when passing in buffers: passing a `Buffer<ocl::aliases::cl_bool>` to a kernel that expects a `__global bool*` caused some `true` values to become `false`. As a workaround I'm now passing in a `Buffer<u8>` to a kernel that takes a `__global char*` and it's working.

**Comment by c0gent** [comment]
Something is amiss. I'd be happy to take a look at your code and see if I can help you sort it out.

**Comment by c0gent** [comment]
Closing this issue.

I'd still like to help you figure out why the kernel native sized bool isn't working for you. I may be able to point you in the right direction (or you point me).

**Comment by yongqli** [comment]
This might have something to do with it. http://stackoverflow.com/questions/4441280/does-opencl-support-boolean-variables

**Comment by c0gent** [comment]
> From Section 6.8.k

>> Arguments to __kernel functions in a program cannot be declared with the built-in scalar types bool, half, size_t, ptrdiff_t, intptr_t, and uintptr_t. The size in bytes of these types except half are implementation-defined and in addition can also be different for the OpenCL device and the host processor making it difficult to allocate buffer objects to be passed as arguments to a kernel declared as pointer to these type

Yeah this is true. That's why `cl_bool` in this library is defined as a `u32` (uint). You can also just use a `u8` (char) if you want... you can use any type you want to represent a boolean as long as you understand how it translates between Rust and OpenCL C.

That's not really what I was curious about though. I'd like to see the code you used which prompted you to say:

> Hmm, I've had a bit of trouble with that when passing in buffers: passing a Buffer<ocl::aliases::cl_bool> to a kernel that expects a __global bool* caused some true values to become false. As a workaround I'm now passing in a Buffer<u8> to a kernel that takes a __global char* and it's working.

I'd like to see the host and kernel code you were running that prompted you to make this comment so I can determine whether this was a mistake or a bug. If it was a mistake, perhaps I can offer some advice on how to avoid repeating it. If it is a bug then I can put on my bug squashing shoes (and hat if necessary... though I try only to bring it out on special occasions...).

**Comment by yongqli** [comment]
I'll try to dig up the code tomorrow.

Isn't the issue that `sizeof(bool)` is implementation defined though? It might not be a `u32` on the device side.

**Comment by c0gent** [comment]
You, the developer, determine what the type of bool is on the device side. 

My advice: do not use the type 'bool' within the kernel (device side). Ever. No reason to. Use int or uint. Use char or uchar if you want to save space. Use any sized type you want as long as it's the same size as the type you're using on the host side.  Remember, C is not a type safe language. The types don't really mean anything other than size (with exceptions in newer versions of C).

The fact that 'bool' is not defined basically means that you just shouldn't use it within a kernel. It's just a relic of bad, or at least inconsistent, design in the C language.

**Comment by yongqli** [comment]
Yeah -- I was surprised that `__global bool*` compiles on OSX. It (correctly) doesn't compile on NVIDIA's compiler.

I'm going to close this issue as it shouldn't be possible to pass in `__global bool*` anyway.
