### ISSUE TITLE
Split out `core` and `ffi` modules

### ISSUE THREAD

**Issue by c0gent** [cogciprocate/ocl#34]
Tracking issue for the breakup of this repo into three pieces.

This will remain the repo for the `standard` types (the highest level interfaces).

### Working Branch:
https://github.com/cogciprocate/ocl/tree/remove_core_ffi

### New Repos:
[cl-sys](https://github.com/cogciprocate/cl-sys) ([crates.io](https://crates.io/crates/cl-sys))
[ocl-core](https://github.com/cogciprocate/ocl-core) ([crates.io](https://crates.io/crates/ocl-core))

- [x] Move out ffi (easy)
  - [x] Docs
  - [x] Publish
- [x] Move out core
  - [x] Docs
  - [x] Publish
- [x] Clean up main repo (this one)
  - [x] Docs

**Comment by c0gent** [comment]
@Kerosene2000, @01d55:

Have a look at the new layout (the two new repos and the new branch, linked above) and let me know what you guys think or if you see anything glaring I've missed.

I'll clean up the documentation and make some new pages for the new crates next.

**Comment by Kerosene2000** [comment]
I saw that you have made many tests for the `ocl` repo and that's great but there is none in the other two new repos (`cl-sys` and `ocl-core`), it can be easy (I think) to move them in the other libs and removing them from the `ocl` crate, no ?
Just asking.

**Comment by c0gent** [comment]
Yep, I sure will :)

**Comment by c0gent** [comment]
@Kerosene2000 would you be willing to fix the `info_core.rs` example in the **ocl-core** repo (https://github.com/cogciprocate/ocl-core/blob/master/examples/info_core.rs) while I continue fixing other issues? It just needs to have the 'standard' parts replaced with 'core' style interfaces the `trivial.rs` example in this repo has an example of this: https://github.com/cogciprocate/ocl/blob/master/examples/trivial.rs#L169.

**Comment by c0gent** [comment]
Also please feel free to move over any tests. I'm going to work on finishing up documentation and publishing crates for the two new repos then I need to spend some time on the new runtime version detection system and the GL interop stuff I want to add.

**Comment by c0gent** [comment]
New documentation and crates are published. The 'remove_core_ffi' branch should be ready to merge.

**Comment by Kerosene2000** [comment]
@c0gent no problem guy, I will do this when I have time, this week-end I think !

**Comment by c0gent** [comment]
Haven't finished the gl stuff I wanted to do yet but the unwraps have arrived!

https://github.com/cogciprocate/ocl-core/commit/6bf323ca81bbb912ccaa29b41b9a90c85b576c2f

**Comment by c0gent** [comment]
Good work on `info_core.rs` by the way. Thanks!

**Comment by Kerosene2000** [comment]
Did you think about reexporting `cl-sys` from `ocl-core` ?

**Comment by Kerosene2000** [comment]
+ Why did you close this issue ?

**Comment by c0gent** [comment]
Yes I'll add that reexport. I think I accidentally closed this.

**Comment by c0gent** [comment]
Pushed to master.
