### ISSUE TITLE
Image example not complete

### ISSUE THREAD

**Issue by drahnr** [cogciprocate/ocl#35]
In the image example misses a `queue().finish()`if I am not mistaken.

At least it was necessary to make a slighlty adjust, GPU only work for me.

**Comment by c0gent** [comment]
Can you please provide more detail of the problem? What exactly is going wrong with the original example?

**Comment by drahnr** [comment]
Sorry for the delay.

The buffer is not always filled when writing to the file.

I will create a PR with an enhanced example to show the problem.

**Comment by c0gent** [comment]
> Sorry for the delay.

No problem at all.


> The buffer is not always filled when writing to the file, this does not seem to happen all the time.

To which file do you refer?


> I will create a PR with an enhanced example to show the problem.

Sounds good. Thanks for your help. We need as much as we can get around here :)

**Comment by drahnr** [comment]
As mentioned I'll try to verify my initial findings with the new `image2` example on the device where this occurred initially.

**Comment by drahnr** [comment]
Ok, I retested this with various states of the example and I think the extra `finish()` after `read()` is unnecessary.

I think I misinterpreted the behaviour/result and the 'fix' was just coincidental with another change, thus I would suggest to close this.

Sorry for the noise.

**Comment by c0gent** [comment]
Also please put in a pull request to update the image2 example to it's correct state. I don't want to chance making any changes that could potentially not work on your platform.

**Comment by drahnr** [comment]
I will do this at some point today.

**Comment by c0gent** [comment]
Don't go to any trouble. If it was a simple bug just say so. I just want to make sure there's no chance of a deeper issue that the library should look out for.

**Comment by drahnr** [comment]
I can not relate the issue to a single commit, nor can I reproduce it right now...

**Comment by c0gent** [comment]
Ok well go ahead and close this issue when you're satisfied. Thanks again.
