### ISSUE TITLE
Panic when no GPUs

### ISSUE THREAD

**Issue by yongqli** [cogciprocate/ocl#39]
It seems that

    let devices = ocl::Device::list(&*OCL_PLATFORM, Some(ocl::core::DEVICE_TYPE_GPU));

will panic if there isn't any GPUs. I was expecting an empty `Vec` instead. Is this intended behavior?

**Comment by j-e-k** [comment]
This occurs whenever `ocl::core:: get_device_ids` does not receive `CL_SUCCESS` as a result of the ffi call to `clGetDeviceIDs`.


I see two options, either to use change the return type to `Result<Vec<Device>>` or to replace the `expect` with `unwrap_or(vec![])`

**Comment by c0gent** [comment]
I agree. Try out the [device_result](https://github.com/cogciprocate/ocl/tree/device_result) branch and let me know how that looks to you two.

**Comment by c0gent** [comment]
@yongqli @j-e-k 

I'm hesitant to add too many convenience functions but would the following be a useful `Device` method?:

```
    /// Returns a list of devices exactly as `::list` does but unwraps any
    /// error and returns an empty `Vec` in the event that the error is a
    /// `CL_DEVICE_NOT_FOUND` variant.
    ///
    /// This is a convenience function.
    ///
    ///
    /// ### Panics
    ///
    /// Panics upon any OpenCL error other than `CL_DEVICE_NOT_FOUND` or any
    /// other type of error.
    ///
    pub fn list_or_empty(platform: &Platform, device_types: Option<DeviceType>)
                -> Vec<Device> {
        match Device::list(platform, device_types) {
            Ok(vec) => vec,
            Err(err) => match err.status() {
                Some(s) => match s {
                    Status::CL_DEVICE_NOT_FOUND => Vec::with_capacity(0),
                    _ => panic!("{}", err),
                },
                None => panic!("{}", err),
            },
        }
    }
```

**Comment by j-e-k** [comment]
Thanks for the fast fix. I don't think `list_or_empty` is particularly necessary (for my use case at least). Using result as you did in #40 is 👍

**Comment by c0gent** [comment]
Alright. If @yongqli is satisfied I'll merge and close this.

**Comment by yongqli** [comment]
@c0gent Thanks, but I don't feel the convenience function is particularly necessary either.

**Comment by c0gent** [comment]
Good enough. Thanks guys.
