### ISSUE TITLE
unwrap() unnecessary on Device and Platform in example code

### ISSUE THREAD

**Issue by skanur** [cogciprocate/ocl#42]
Code in `examples` directory use `unwrap()` on variables of type `Device` and `Platform`. This is unnecessary and code doesn't compile.

For Eg:
at line 40 of [info.rs](https://github.com/cogciprocate/ocl/blob/master/examples/info.rs)
```rust
let devices = Device::list_all(platform).unwrap();
```

**Comment by c0gent** [comment]
Which version of ocl are you testing with? This was a recently made change and it seems as though you may have examples from the newest version yet libraries from an older one.

Have you tested this with a fresh clone of [master](https://github.com/cogciprocate/ocl.git)?

**Comment by skanur** [comment]
Yes! I confirm that is the problem. I tried with master and it is alright! My mistake!
