### ISSUE TITLE
Null terminators present in Strings

### ISSUE THREAD

**Issue by remexre** [cogciprocate/ocl#48]
```rust
extern crate ocl;

use ocl::*;

fn main() {
    for platform in Platform::list() {
        println!("platform: {:?}", platform.name());
        for device in Device::list_all(&platform) {
            println!("device: {:?}", device.name());
        }
    }
}
```

got

```sh
$ cargo run
     Running `target/debug/test`
platform: "Intel(R) OpenCL\u{0}"
device: "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz\u{0}"
```

expected

```sh
$ cargo run
     Running `target/debug/test`
platform: "Intel(R) OpenCL"
device: "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz"
```

In nine or ten hours I can test this with Nvidia's ICD too, right now I only have my laptop.

**EDIT**: So at a minimum, the following methods return null terminated strings with Intel's ICD:

 * Platform::name()
 * Platform::profile()
 * Platform::version()
 * Platform::vendor()
 * Platform::extensions()
 * Device::name()
 * Device::vendor()

The following methods do not:

 * Platform::into()
 * Device::into()
 * Device::to_string()

(test program [here](https://gist.github.com/remexre/d7716a86edd84811f8cc4a801173be15))

**Comment by c0gent** [comment]
The source byte arrays are run through [String::from_utf8](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8). They could be passed through a `CString` instead but I'm not really sure it matters.

All of the `...Info` types implement `Display` so I would simply recommend printing them with `{}`.

Feel free to convince me otherwise. Is there a case you can think of where it matters?

**Comment by c0gent** [comment]
By the way the relevant file is: https://github.com/cogciprocate/ocl-core/blob/master/src/types/enums.rs.

**Comment by remexre** [comment]
Piping stdout to another tool. I can make an example to prove it later, but I'm pretty sure this'd cause JSON-serialized output to not match string-comparison with e.g. [`jq`](https://stedolan.github.io/jq/).

**Comment by c0gent** [comment]
Examples of the original conversion (from byte arrays):

https://github.com/cogciprocate/ocl-core/blob/master/src/types/enums.rs#L112
https://github.com/cogciprocate/ocl-core/blob/master/src/types/enums.rs#L516

**Comment by c0gent** [comment]
Well that would depend on how you exported to JSON but yes that would certainly be a risk. 

Good catch. Feel free to submit a pull request running the bytes through a `CString` then to a `String`. :)

**Comment by c0gent** [comment]
Are you sure that `String` doesn't keep a null terminator just beyond the end of the string and maybe that's what `Debug` is showing? I seem to remember that it used to but I could easily be mistaken...

**Comment by remexre** [comment]
```rust
extern crate ocl;

use ocl::Platform;

fn main() {
    println!("{:?}", Platform::default().name());
    println!("{:?}", "Hello world");
}
```

```sh
$ cargo run
     Running `target/debug/testificate`
"Intel(R) OpenCL\u{0}"
"Hello world"
```

**Comment by c0gent** [comment]
Heh yea. Just tested that myself too.

**Comment by remexre** [comment]
Yeah, not seeing a "nice" way to do this... I'll send a PR after sunup or on Tuesday.

**Comment by c0gent** [comment]
Sounds good.
