### ISSUE TITLE
How does one map buffers?

### ISSUE THREAD

**Issue by skanur** [cogciprocate/ocl#50]
I see `enqueue_map_buffer` command in ocl_core module. What is the corresponding call in ocl? I went through the code of Buffer module and I couldn't find any calls to `enqueue_map_buffer`. Am I missing something?

**Comment by c0gent** [comment]
You're not missing anything. It's not yet implemented in `ocl`. 

If I remember correctly, I was waiting to implement this at a high level until I could devise a safe mechanism for managing mapped buffers, a la [Glium](https://github.com/tomaka/glium).

For now you can just used the pointer returned by `core::enqueue_map_buffer` to create a [`Vec` from parts](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.from_raw_parts), a [slice](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html) or just access it directly with pointer math.

I'd love to see any implementation ideas you have about a `MappedBuffer` type. I need to add that to the library.

**Comment by skanur** [comment]
Thanks for clarifying that. 

For now I'll try to use `core::enqueue_map_buffer` as it is. I might have a question or two about this in coming days. I'll keep this issue open until then and close it later.

For now, I can't think of any way to implement it as a part of `Buffer` struct. I'll think on it too, when I have some free time and get back to you.

**Comment by skanur** [comment]
I was able to use `core::enqueue_map_buffer` successfully. [Here](https://gitlab.com/snippets/29189) is a snippet that lists one possible way to map and unmap buffers.

**Comment by c0gent** [comment]
Ok great. At some point I want to add a 'safe' interface for this. Let me know if you happen to have any ideas.

**Comment by c0gent** [comment]
Would you mind adding that snippet to the project's examples? Or may I?

**Comment by skanur** [comment]
I have submitted a pull request.
