### ISSUE TITLE
Releasing buffers

### ISSUE THREAD

**Issue by haxelion** [cogciprocate/ocl#52]
Hey,

I don't see any way of explicitly releasing a buffer and I don't see either an implicit release via the drop trait.
Am I wrong ?

I can implement it if you tell me what you would prefer between implicit and explicit release.

Cheers

**Comment by c0gent** [comment]
https://github.com/cogciprocate/ocl-core/blob/master/src/types/abs.rs#L465

**Comment by haxelion** [comment]
Oooh my bad, I see now the MemCore member.
Sorry I stupidly searched the repo for "impl Drop" and "release_mem_object" :/

Thanks :)

**Comment by c0gent** [comment]
No problem. Thanks for the offer to implement it.

Keep your eyes open, you'll probably find something that needs doing. :)

**Comment by haxelion** [comment]
Yes I'll be glad to help if I can ;)
