### ISSUE TITLE
Accessing SubBuffers

### ISSUE THREAD

**Issue by botev** [cogciprocate/ocl#58]
So this might be a very basic question as I'm new to OpenCL and thus working out this in Rust is even more challenging. Essentially I want to allocate a very large buffer of memory in the OpenCL context and be able to look only at specific parts for specific kernels (e.g. to have my own memory manager). I've saw that the standard OpenCL has SubBuffers. Would it be possible to add at some point an example of how this would look in Rust? 
Thanks!

**Comment by c0gent** [comment]
OpenCL and Rust are each a challenge to learn but well worth the effort as they combine beautifully once you start doing the really complex stuff. I'm happy to help.

It's funny that you mention sub-buffers as I'm about to implement them in the top level library (ocl).

For your purposes however, you don't necessarily need to create sub-buffers (though they are a perfectly fine option). You can simply pass an 'offset' argument to your kernels to access sub-regions as necessary. If your sub-regions are equally sized, you can use the OpenCL dimensions to calculate the correct index offset within the buffer for each work item (or however else you want to do it).

Give me a little bit more information about what you're trying to do and I'll put together a quick example or two for you.

**Comment by botev** [comment]
Cool. Any help would be most appreciated. I'm working on this: https://github.com/Metadiff/gir. Let me briefly explain what it is and what I wanted it to do, in fact you might have a much better opinion of how to do it well. 

So you can think of GIR as a compiler for HPC with autodiff, which compiles a whole function. This means two things: you are limited to mainly maths operations (e.g. no control flow), but on the other hand you know priori the whole graph of the function. This is something getting popular in ML these days. The benefit is that it allows you to do a lot optimizations, which for function which will be repeatedly called, e.g. training for 100000 iterations of the same function call, can greatly improve run times. Optimization may include constant propagation - SVD of some fixed matrix, which does not change between function calls, can be precomputed. Kernel fusion - tanh(W*h+b) rather than having 3 kernels executing this you can have only 1. Additionally, it should be able to generate ad-hoc kernels base on the concrete problem at hand, rather than using a fixed number of handly written. And all this should happen automatically, such that the user only builds the mathematical equations (and you get autodiff which means gradients procedures are generated automatically). There are however two aspects of this - the IR which represents the abstract computation and the backend, which actually takes a graph and executes it on a device. Now I have made a small example with which if you clone the repo can run and copy paste the printed output to http://www.webgraphviz.com/ to see how the graph looks. Now I have so far implemented a very small subset of all base operations, but I want to now make a backend which can execute these - OpenCL.

One of the major optimizations in this setting is memory recycling - since when optimizing you know the whole program and you specify the schedule you know when certain arrays are no longer needed, thus for future ones you can reuse their buffers (this is more or less similar to how register allocation works). Additionally, you can compute a static layout of the whole memory for every single operation. This however essentially means  that I need to have a memory pool - quite large - which I pre allocate. This pool will contain the maximum memory required at any point of the function. When the function executes each single node will have just an offset based on the static layout in that memory. Essnetially, I need to be able to call a kernel on smth like:
```
on host:
call_kernel(memory_pool, offset_a, offset_b, n) 
and the kernel to do:
memory_pool[offset_a + global_id] = memory_pool[offset_b + global_id]
```

One of the things so far I did not understand about OpenCL is if it gives guarantee that the memory is contiguous and if pointer arithmetic like this works? (I think 2.0+ does and earlier don't)?

Sorry for the long reply and again my knowledge of OpenCL is novice. Could you by any chance and point me to a good guide on intro to it?

**Comment by c0gent** [comment]
First, the best guide I've seen, and an invaluable reference when learning OpenCL, is [OpenCL in Action](https://www.amazon.com/OpenCL-Action-Accelerate-Graphics-Computations/dp/1617290173/ref=sr_1_1?ie=UTF8&qid=1486101820&sr=8-1&keywords=opencl+in+action). I'd recommend purchasing it as good authors of obscure technical subjects need all the support they can get. If you can't afford it though, you'll have no trouble finding it on a notorious *ahem* and somewhat less reputable web site.

> One of the things so far I did not understand about OpenCL is if it gives guarantee that the memory is contiguous and if pointer arithmetic like this works? (I think 2.0+ does and earlier don't)?

OpenCL buffers are certainly contiguous and are exactly analogous to heap memory allocated via malloc, et al. Just a pointer and a size is all that describes them. You can and generally must do pointer/index arithmetic all the time.

> So you can think of GIR as a compiler for HPC with autodiff ... I want to now make a backend which can execute these - OpenCL.

You're in the right place. Rust is probably the ideal combination of performance and usability/maintainability for a project like this.

As for your memory allocation strategy, for your purposes sub-buffers will in fact be a more convenient way to manage memory and were designed to do pretty much exactly what you want to do. Again, you can achieve the same thing by just passing an offset but if certain sections of a buffer will be reused a few times, it's a nice bookkeeping convenience to have a way to keep track of them and coordinate between host and device.  

I'll have time in the next week or so to implement them into the library. I've been dragging my feet so the fact that someone might need to use a feature usually gets me moving. I'll put together an example to get you started once I've got that done. Let me know if you have any other questions in the meanwhile and check out that book.

**Comment by c0gent** [comment]
@botev:
It's a rainy Sunday here in California so I went ahead and finished up adding sub-buffers, mapped buffers, and [put together an example for you](https://github.com/cogciprocate/ocl/blob/master/examples/alloc_async.rs). Hopefully it gives you a few ideas or at least gets you pointed in the right direction.

Let me know how it goes :)

**Comment by botev** [comment]
Oh, thanks a lot, that would be most helpful. I will take a look during the week and try my best to understand everything (I'm still early in the book, but started to get the idea of Context, Queues, etc...). 

Actually on a side note, if you are interested in ML, since in general on my project so far we lack anyone with a good understanding of lower level things, like opencl for instance, could I invite you whenever you do have some time or just want to visit the gitter channel for some chat.

**Comment by c0gent** [comment]
I used to spend a lot of time on ML. I've moved away from it and I currently spend a lot of my extra time working a neuroscience inspired cortical learning toolkit called [bismit](https://github.com/cogciprocate/bismit). I might stop in and say hi sometime though :)

**Comment by botev** [comment]
Am currently I get some compiler errors from the `ocl-core` even with the GitHub link replacement:
```
error[E0432]: unresolved import `core::MappedMem`
  --> src/standard/buffer.rs:13:46
   |
13 |     ClEventPtrNew, ClWaitList, BufferRegion, MappedMem as MappedMemCore, Event as EventCore,
   |                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^ no `MappedMem` in the root

error[E0087]: too many type parameters provided: expected at most 0 parameters, found 1 parameter
    --> src/standard/buffer.rs:1017:50
     |
1017 |         let obj_core = core::create_sub_buffer::<T>(buffer, flags,
     |                                                  ^ too many type parameters

error: no associated item named `new` found for type `core::BufferRegion` in the current scope
    --> src/standard/buffer.rs:1018:14
     |
1018 |             &BufferRegion::new(origin.to_len(), size.to_len()))?;
     |              ^^^^^^^^^^^^^^^^^
```

**Comment by c0gent** [comment]
Yeah you temporarily have to add:

```
[replace]
"ocl-core:0.3.2" = { git = "https://github.com/cogciprocate/ocl-core" }
```

to all of your `Cargo.toml`s all the way up your stack until the new ocl-core is published to crates.io.

**Comment by c0gent** [comment]
And do a cargo update.

**Comment by c0gent** [comment]
Closing this for now. Let me know if you have any other problems or questions.
