### ISSUE TITLE
Example code does not compile

### ISSUE THREAD

**Issue by coder543** [cogciprocate/ocl#6]
I'm getting compile errors for the example code on the main github page.

```
src/main.rs:1:21: 1:29 error: unresolved import `ocl::ProQueue`. There is no `ProQueue` in `ocl` [E0432]
src/main.rs:1 use ocl::{ Context, ProQueue, BuildOptions, SimpleDims, Envoy };
                                  ^~~~~~~~
src/main.rs:1:21: 1:29 help: run `rustc --explain E0432` to see a detailed explanation
src/main.rs:1:31: 1:43 error: unresolved import `ocl::BuildOptions`. There is no `BuildOptions` in `ocl` [E0432]
src/main.rs:1 use ocl::{ Context, ProQueue, BuildOptions, SimpleDims, Envoy };
                                            ^~~~~~~~~~~~
src/main.rs:1:31: 1:43 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `ocl_test`.

To learn more, run the command again with --verbose.
```
Even though it downloads and compiles the `ocl` dependency successfully, and `clinfo` seems to indicate opencl support is working just fine on my system.

What could be wrong? I'm guessing something has changed in the library recently, but the 'unresolved' objects seem to be in the library. I'm not yet familiar enough with Rust to say what's going on for sure.

**Comment by c0gent** [comment]
Make sure you have the following in your Cargo.toml:

```
[dependencies]
ocl = "0.2"
```

If you want to always have the latest version of any crate you can also use `*` as the version number (keep in mind this can be annoying if the crate is unstable)  i.e.:

```
[dependencies]
ocl = "*"
```

Let me know if that fixes it.

**Comment by coder543** [comment]
My Cargo.toml looks like this:

```
[package]
authors = ["Josh Leverette <...>"]
name = "ocl_test"
version = "0.1.0"

[dependencies]
ocl = "0.2"
```

It seems to download and compile the ocl package, but it doesn't find the ProQueue and BuildOptions items.

I've uploaded my repository here: https://github.com/coder543/ocl_test

I think playing with OpenCL in Rust could be a lot of fun, so I hope to understand what's going on.

**Comment by c0gent** [comment]
Completely my fault... I didn't update first few lines of the example in the README last time I made changes. Should be: 

```
use ocl::{ Context, BuildConfig, Envoy, SimpleDims, ProQue };
extern crate ocl;
```

Thanks for finding this!

**Comment by c0gent** [comment]
Please keep those questions coming. There's a lot lacking in the documentation department. Please let me know which areas I should focus on first (i.e. what is the most confusing or unclear).
