### ISSUE TITLE
Cargo update because of hard coded paths in the examples

### ISSUE THREAD

**Issue by botev** [cogciprocate/ocl#62]
So recently I got this weird error from cargo:
```
alex@botev-ThinkPad-T440:~/work/metadiff/gir$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/cogciprocate/ocl/`
error: failed to load source for a dependency on `ocl`

Caused by:
  Unable to update https://github.com/cogciprocate/ocl/

Caused by:
  Could not find `Cargo.toml` in `/home/nick/src/github.com/cogciprocate/ocl-core`
```
The only place I found this path being hard coded is in the examples directory files, but it brakes my builds which work with the github head. Could you remove those?

**Comment by c0gent** [comment]
Yeah sorry about that... I tend to forget about those from time to time.

e7efa21cad4a04f0f2810d43c30b3ba6dbc2b305
