### ISSUE TITLE
Example for reading a scalar out

### ISSUE THREAD

**Issue by bright-star** [cogciprocate/ocl#70]
This is not a bug report at all, but I was curious, what is the recommended way to read a scalar shared in a kernel? I see that `arg_scl` can pass in a bunch of scalar `OclPrm` types, and they can also be passed in by creating a buffer out of their mutable reference. But if you try to read back from that buffer into the scalar ref, the buffer read method will expect a trait that is not implemented for scalar types:

```
error[E0277]: the trait bound `ocl::standard::buffer::ReadDst<'_, f64>: std::convert::From<&mut f64>` is not satisfied
```

What's the recommended way to do this?

Also, thanks for making this library. It's excellent already.

**Comment by c0gent** [comment]
Thanks for the feedback and the compliment. 

Very interesting question. The answer is complicated....

I've been meaning to start [this gitter chat channel](https://gitter.im/cogciprocate/ocl) for a while. If you don't mind, I'd like to move the conversation there. Even better, if you have voice chat I'd be interested to ask you some more questions about your question (and provide some answers).

**Comment by bright-star** [comment]
So as mentioned in the chat, here's a kernel that computes a 1-tap LMS filter:

```rust
static KERNEL_SRC: &'static str = r#"
    __kernel void lms(
               __private uint const sig_len,
               __global double const* signal,
               __global double const filt_coef,
               __global double* const pred)
    {
        double step_size = 0.05;

        pred[0] = 0.0;

        for (uint n = 1; n < sig_len; n++) {
            double const cur_pred = filt_coef * signal[n - 1];
            double err = signal[n] - cur_pred;
            filt_coef += step_size * signal[n - 1] * err / (pown(signal[n - 1],2) + DBL_EPSILON);
            pred[n] = cur_pred;
        }
    }
"#;
```

If you try to invoke `Buffer::read` with a mutable scalar reference as its argument, you get the expected type error:

```rust
  let mut filter_coef: f64 = 0.5;

  let ocl_pq = ProQue::builder()
    .src(KERNEL_SRC)
    .dims(signal_len)
    .build().expect("Build ProQue");

  let signal_buffer = Buffer::builder()
    .queue(ocl_pq.queue().clone())
    .flags(MemFlags::new().read_write().copy_host_ptr())
    .dims(ocl_pq.dims().clone())
    .host_data(&sig_vec)
    .build().unwrap();

  let filt_buffer = Buffer::builder()
    .queue(ocl_pq.queue().clone())
    .flags(MemFlags::new().read_write().copy_host_ptr())
    .dims(1)
    .host_data(&[filter_coef])
    .build().unwrap();

  let mut pred: Vec<f64> = vec![0.0; signal_len];

  let pred_buffer: Buffer<f64> = ocl_pq.create_buffer().unwrap();

  let kern = ocl_pq.create_kernel("lms")
                   .unwrap()
                   .arg_scl(signal_len)
                   .arg_buf(&signal_buffer)
                   .arg_buf(&filt_buffer)
                   .arg_buf(&pred_buffer);

  println!("Kernel global work size: {:?}", kern.get_gws());

  kern.enq().unwrap();

  pred_buffer.read(&mut pred).enq().unwrap();
  filt_buffer.read(&mut filter_coef).enq().unwrap();
```

Here's a [gist](https://gist.github.com/bright-star/b69e6e779ef176e4d917daab5a9e52ff#file-single-rs) of the whole code.

**Comment by c0gent** [comment]
Yeah I'm with you now... Since the error you were getting was from a brand new type (`ReadDst`) I wanted to make sure that there wasn't anything else wrong with it.

Yes, the scalar arguments are always one-way and are always copied just in the same way passing a scalar to a function in C or Rust, etc. Outputs from a kernel are always contained in a buffer (any `cl_mem` abstract object type), even if that buffer has only length one.

Sorry to run you around from chat to here. I haven't been at home :)

Feel free to ask any other questions. The chat is the best place for general questions and I'm happy to answer them (I always learn something from it).
