### ISSUE TITLE
Derive PartialEq and Eq for SpatialDims

### ISSUE THREAD

**Issue by michael-p** [cogciprocate/ocl#71]
It would be very nice if `SpatialEq` would implement/derive `Eq` and `PartialEq`!
Small improvement, but really useful!

Thank you very much!

**Comment by c0gent** [comment]
Absolutely. Might I recommend a pull request? :)

**Comment by michael-p** [comment]
Absolutely :) I wasn't sure whether you would prefer a PR for such a small change, but there you go! :)

**Comment by c0gent** [comment]
Yeah I'm just not on my main PC and also I'm lazy :P

**Comment by michael-p** [comment]
Hi Nick, any plans to release a new version to crates.io with the changes here and those of #67 and #66 anytime soon? :)
I really don't want to push you, we can continue working with a local fork, but just wanted to notify you that these really nice changes haven't yet made it into the officially blessed crates.io version ;)

Thanks
Michael

**Comment by c0gent** [comment]
Absolutely. Please feel free to push me, otherwise I'll just stand there daydreaming :P

0.13.2 is up :)

**Comment by c0gent** [comment]
There was a tiny breakage so 0.13.2 was yanked. 

0.14.0 is up instead :)

**Comment by michael-p** [comment]
Thanks a lot!
However, there seems to be a problem with `ocl-core` compatibility right now resulting in following compile errors:
```
error[E0432]: unresolved import `core::ImageFormatParseResult`
  --> /Users/michaelp/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.14.0/src/standard/image.rs:16:67
   |
16 | use core::{self, OclPrm, Mem as MemCore, MemFlags, MemObjectType, ImageFormatParseResult,
   |                                                                   ^^^^^^^^^^^^^^^^^^^^^^ no `ImageFormatParseResult` in the root

error[E0119]: conflicting implementations of trait `core::ClDeviceIdPtr` for type `&standard::device::Device`:
   --> /Users/michaelp/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-0.14.0/src/standard/device.rs:513:1
    |
513 |   unsafe impl<'a> ClDeviceIdPtr for &'a Device {
    |  _^ starting here...
514 | |     fn as_ptr(&self) -> cl_device_id {
515 | |         self.0.as_raw()
516 | |     }
517 | | }
    | |_^ ...ending here
    |
    = note: conflicting implementation in crate `ocl_core`
```

Interestingly, ocl master compiles but when using `ocl` in an application compilation files with above message:
```
~/Desktop $ cargo new --bin ocl_demo
     Created binary (application) `ocl_demo` project
~/Desktop $ cd ocl_demo/
~/Desktop/ocl_demo (master #) $ cargo add ocl
~/Desktop/ocl_demo (master #) $ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling cl-sys v0.3.0
   Compiling ocl-core v0.4.1
   Compiling ocl-core-vector v0.1.0
   Compiling ocl v0.14.0
 [...] more stuff and above errors
```

**Comment by c0gent** [comment]
Thanks for catching that. Version 0.14.1 should straighten everything out (I hope).
