### ISSUE TITLE
clGetGLContextInfoKHR only available in cl_sys

### ISSUE THREAD

**Issue by Nopey** [cogciprocate/ocl#77]
This function is important for issue #23 because it allows developers of an application to pick a device for OpenCL that will be able to interoperate with a OpenGL context.
This is only important when there are multiple compute devices available, and just picking one willy nilly could cause a `CL_INVALID_GL_SHAREGROUP_REFERENCE_KHR` to be tripped
Here is [the SDK link](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetGLContextInfoKHR.html)
and [the related issue on `ocl-interop`](https://github.com/Nopey/rust-ocl-interop/issues/1)

**Comment by c0gent** [comment]
https://github.com/cogciprocate/ocl-core/commit/d53f8fe99c30453284f83a1c7718ea302b621149
