### ISSUE TITLE
error: local ambiguity: multiple parsing options: built-in NTs ident ('variant') or 1 other option.

### ISSUE THREAD

**Issue by NerDee** [cogciprocate/ocl#81]
This error message keeps popping up when I try to compile a blank project with the library.
I have a GTX 960 and I'm running this on Ubuntu.
Here is the full log...

   Compiling ocl-core v0.6.0
error: local ambiguity: multiple parsing options: built-in NTs ident ('variant') or 1 other option.
   --> /home/damon/.cargo/registry/src/github.com-1ecc6299db9ec823/ocl-core-0.6.0/src/lib.rs:871:9
    |
871 |         /// Return the CL device currently associated with the specified OpenGL context.
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: Could not compile `ocl-core`.

To learn more, run the command again with --verbose.

**Comment by c0gent** [comment]
What's your compiler version (`rustc --version`)?

**Comment by NerDee** [comment]
1.19.0

**Comment by c0gent** [comment]
Strange... Try using the following override in your project's `Cargo.toml`. There may have been a quirk related to a doc comment. I just removed it.

```
[replace]
"ocl-core:0.6.0" = { git = "https://github.com/cogciprocate/ocl-core" }
```

**Comment by NerDee** [comment]
Weird, I just ran 'rustup update stable' and now it works

**Comment by NerDee** [comment]
It works on 1.20.0

**Comment by c0gent** [comment]
Heh, I'll take it.
