### ISSUE TITLE
Compiling ocl fails with Mesa / Clover on Linux

### ISSUE THREAD

**Issue by Fluxie** [cogciprocate/ocl#83]
Mesa / Clover does not support functonality related to context sharing with OpenGL and it does not implement the functions in the library. Thus attemping to compile ocl with mesa as the vendor fails due to undefined references to clEnqueueAcquireGLObjects and  clEnqueueReleaseGLObjects functions.

Error:
"
In function `<ocl::standard::buffer::BufferCmd<'c, T>>::enq':
          ocl_test.cgu-0.rs:(.text._ZN64_$LT$ocl..standard..buffer..BufferCmd$LT$$u27$c$C$$u20$T$GT$$GT$3enq17h0b908b3c1978ab85E+0x23f): undefined reference to `clEnqueueAcquireGLObjects'
          ocl_test.cgu-0.rs:(.text._ZN64_$LT$ocl..standard..buffer..BufferCmd$LT$$u27$c$C$$u20$T$GT$$GT$3enq17h0b908b3c1978ab85E+0x3b0): undefined reference to `clEnqueueReleaseGLObjects'
          collect2: error: ld returned 1 exit status
"

I don't know the mesa nor opencl stack but the functions causing problems are also missing from here.
https://cgit.freedesktop.org/mesa/mesa/tree/src/gallium/state_trackers/clover/api/dispatch.cpp

I already hacked together a feature flag "opencl_vendor_mesa" that I used to exclude the functionality that caused the problems. I was then able to run "ocl/examples/trivial.rs" succesfully. If you find the feature flag approach acceptable I will try to create a proper fix and exclude all functionality related to context sharing with OpenGL. Although at the moment I'm not sure what else should be excluded as this is my first attempt at opencl.

Changes I had to do to compile ocl with Mesa:
https://github.com/Fluxie/cl-sys/commit/4b9a9cf75e26d7d523084ea3aacf8083bf009cb1
https://github.com/Fluxie/ocl-core/commit/9b5740729549ba58eeddb6cbd1c5ceea4dfea245
https://github.com/Fluxie/ocl/commit/7a807262f88992c71faebbe3a99491ef47c9c18f

**Comment by c0gent** [comment]
I like your approach. A pull request with those changes would be welcome :)

**Comment by c0gent** [comment]
The changes you've made are perfect as is. Go ahead and submit a pull request with the changes you've already made.

If you have any questions or need help with anything else, don't hesitate to ask :)
