### ISSUE TITLE
Use a workspace for the whole project

### ISSUE THREAD

**Issue by Kerollmops** [cogciprocate/ocl#85]
I know that you have already separated the project in three parts.

But for `ocl` it doesn't seems to be a great choice, it depends on `ocl-core` and `cl-sys`. And you let [temporary comments to the `Cargo.toml`](https://github.com/cogciprocate/ocl/blob/ee887df312fefbfddc7d73f168927f52eeab2e3e/Cargo.toml#L51-L56) that you have to remember uncommenting on the next release you'll push to http://crates.io.

Why not follow the http://Rocket.rs example and use a [pretty workspace](https://github.com/SergioBenitez/Rocket/) that let your repository separate but unified at the same time ?

For Rocket, the repository is composed of the main [rocket lib](http://docs.rs/rocket/), [rocket codegen](https://docs.rs/rocket_codegen/0.3.2/) and [rocket contrib](https://docs.rs/rocket_contrib/).

You'll not have any worry on the `Cargo.toml` dependencies anymore and will always publish releases of the three libraries at the same time (and with the same minor/major revision number for more clarity). All [the dependencies can have a relative path](https://github.com/SergioBenitez/Rocket/blob/master/contrib/Cargo.toml#L24) to let you work on your own computer with more ease.

**Comment by c0gent** [comment]
Absolutely. I've been meaning to do this for a while. Maybe I'll finally get around to it this week.

Thanks for reminding me :)

**Comment by c0gent** [comment]
Done!

Let me know what you think.

**Comment by c0gent** [comment]
TODO: Fix links in README, etc.

**Comment by Kerollmops** [comment]
That seems great for me ! 🎉

I am actually writing a list of things that can be improved in the library. For example following the [Rust api guideline](https://rust-lang-nursery.github.io/api-guidelines), changing the way `Buffer`, `Program` and other Types works. I will publish that when I'm done.

**Comment by c0gent** [comment]
Interesting. Looking forward to it.

**Comment by Kerollmops** [comment]
Whew... !

I though I loose the temporary file with all the improvements I promised you but here it is [ocl improments](https://gist.github.com/Kerollmops/68fc37f049c57efc7c77e420da300e3b).

I am not done with it, don't take this into account for the moment, I continue working on it.

**Comment by c0gent** [comment]
I've created a new issue for discussion:

https://github.com/cogciprocate/ocl/issues/89
