### ISSUE TITLE
Tests fail on OS X

### ISSUE THREAD

**Issue by lattwood** [cogciprocate/ocl#9]
No idea where to start.

```
running 2 tests
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'assertion failed: `(left == right)` (left: `326`, right: `306`)assertion failed: `(left == right)` (left: `326`, right: `316`)', ', src/tests.rssrc/tests.rs::3232

libc++abi.dylib: libc++abi.dylib: terminating with uncaught foreign exceptionterminating with uncaught foreign exception
```

**Comment by c0gent** [comment]
It's probably just something screwy with that particular test, which I just tossed together and haven't touched in a while. For now just comment out line 32 of tests.rs or just remove the `test_events()` function and I'll have a look at it sometime soon.

**Comment by c0gent** [comment]
Just made that change on master.

**Comment by c0gent** [comment]
Would be curious to know how things are working on OS X before I close this issue.

**Comment by lattwood** [comment]
I'll try to take a look this weekend. Unfortunately I needed to use the OpenCL image APIs and I wasn't about to learn Rust and OpenCL while building out the OpenCL functions I needed in Rust- that's a bit of a steep learning curve.

Ended up going with this golang lib unfortunately, it had the needed wrapper functions :-/

https://github.com/xfong/go-opencl/blob/master/cl/image.go

**Comment by c0gent** [comment]
I'm about to add image support to this library, would appreciate another look in a few weeks and possibly some feedback.

**Comment by lattwood** [comment]
Looking forward to it.

**Comment by c0gent** [comment]
Just pushed version 0.7. The new [`Image`] type has most of the basic stuff implemented. I'd like to maybe add some sort of mechanism so that different sized format channels and data_types provide some guidance on the type and size of vector needed to work with them but I'm not sure how much assistance is too much.

Having zero experience with OpenCL images myself, I'd really appreciate your feedback and even design ideas if you have any.

Links: [`Image`], [`ImageBuilder`], [`examples/image.rs`]

[`Image`]: http://doc.cogciprocate.com/ocl/struct.Image.html
[`ImageBuilder`]: http://doc.cogciprocate.com/ocl/struct.ImageBuilder.html
[`examples/image.rs`]: https://github.com/cogciprocate/ocl/blob/master/examples/image.rs

**Comment by neverfox** [comment]
This may be related in that the error looks similar to one I get running the events example panics (on OS X with an Intel Iris Pro GPU). Here's the output:

```
Enqueuing kernel [itr:0]...
Enqueuing read buffer [itr:0]...
Setting callback (verify_result, buncha_stuff[0]) [i:0]...
Enqueuing kernel [itr:1]...
Enqueuing read buffer [itr:1]...

Event: `0x7fadd33004d0` has completed with status: `0`, data_set_size: '262144`, addend: 11, itr: `0`.
correct_result: 448, result_vec[0]:448
correct_result: 18, result_vec[1]:18
correct_result: 261, result_vec[2]:261
correct_result: 213, result_vec[3]:213
correct_result: 488, result_vec[4]:488
Setting callback (verify_result, buncha_stuff[1]) [i:1]...
Enqueuing kernel [itr:2]...

Event: `0x7fadd0d0a3b0` has completed with status: `0`, data_set_size: '262144`, addend: 11, itr: `1`.
correct_result: 459, result_vec[0]:459
correct_result: 29, result_vec[1]:29
correct_result: 272, result_vec[2]:272
correct_result: 224, result_vec[3]:224
correct_result: 499, result_vec[4]:499
Enqueuing read buffer [itr:2]...
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `317`, right: `306`)', examples/events.rs:52
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Setting callback (verify_result, buncha_stuff[2]) [i:2]...
thread '<unnamed>' panicked at 'assertion failed: `(left == right)` (left: `265`, right: `254`)', libc++abi.dylib: examples/events.rs:52
terminating with uncaught foreign exceptionEnqueuing kernel [itr:3]...


Event: `0x7fadd33008d0` has completed with status: `0`, data_set_size: '262144`, addend: 11, itr: `2`.
libc++abi.dylib: %
```

**Comment by c0gent** [comment]
@neverfox 

Alright let's get to the bottom of it... Would you mind creating a new issue and just referencing this one?

**Comment by neverfox** [comment]
Sure thing, @c0gent.
