### ISSUE TITLE
OpenCL 1.0 thread unsafety

### ISSUE THREAD

**Issue by rNoz** [cogciprocate/ocl#91]
In the readme:

> Version Support
> OpenCL versions 1.1 and above are supported. OpenCL version 1.0 is not supported due to its inherent thread unsafety.

Extracted from [clSetKernelArg 1.1](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clSetKernelArg.html):
> An OpenCL API call is considered to be thread-safe if the internal state as managed by OpenCL remains consistent when called simultaneously by multiple host threads. OpenCL API calls that are thread-safe allow an application to call these functions in multiple host threads without having to implement mutual exclusion across these host threads i.e. they are also re-entrant-safe.
> All OpenCL API calls are thread-safe except clSetKernelArg, which is safe to call from any host thread, and is safe to call re-entrantly so long as concurrent calls operate on different cl_kernel objects. However, the behavior of the cl_kernel object is undefined if clSetKernelArg is called from multiple host threads on the same cl_kernel object at the same time. 

Do you refer "thread unsafety" to this? 

> The support for different hosts gives possibilities for cloud-computing. Side-note: cloud-computing is another word for multi-user environments, with some promotion for big data-centres. All API-functions except clSetKernelArg are thread-safe now; but only when kernels are not shared between hosts; see appendix A.2 for more information. The important part is that you think clearly about how to design your software if you now can assume others can take your resources now too. OpenCL already needed a lot of planning when claiming and releasing resources, so you’re probably already mastering it; now just check more often how much resources are available.

**Comment by c0gent** [comment]
`clSetKernelArg` is not thread-safe but that's not what I was referring to.

From the [OpenCL 1.0 spec](https://www.khronos.org/registry/OpenCL/specs/opencl-1.0.pdf), Appendix A.2:

> A.2 Multiple Host Threads
>
> The OpenCL implementation is thread-safe for API calls that create, retain and release objects
> such as a context, command-queue, program, kernel and memory objects. OpenCL API calls
> that queue commands to a command-queue or change the state of OpenCL objects such as
> command-queue objects, memory objects, program and kernel objects are not thread-safe.
> The OpenCL implementation should be able to create multiple command-queues for a given
> OpenCL context and multiple OpenCL contexts in an application running on the host processor.

Basically what this means is that in OpenCL 1.0, queues, buffers, images, programs, and kernel objects are not thread safe for most operations. Simply enqueuing a task to the same queue from two different threads could lead to undefined behavior. On the other hand, these objects in OpenCL 1.1 and above use internal synchronization mechanism to ensure thread safety.

If we wanted to be extremely ambitious, we could support OpenCL 1.0 safely but it would require implementing the synchronization mechanisms ourselves. This would be a huge effort and massive extra complexity.

**Comment by rNoz** [comment]
Thank you very much.

I am completely new to Rust, so, impossible for me right now. And I have started to test your project (ocl) and I have seen unimplemented features (like `core::get_program_info(&program, core::ProgramInfo::Binaries` that I am struggling with) that are more important to get a final complete version.

**Comment by c0gent** [comment]
Oh, do you need `ProgramInfo::Binaries`? If it's not implemented I can wire it up pretty easily.

**Comment by rNoz** [comment]
It will be great. I was checking enums.rs and functions.rs and got the direction of how to do it, but my Rust knowledge is a bit low yet (I thought It will be something close to `::Source` but with `u8` instead of `c_char` or `CString`).

Apart from that, your library is great. I am using the "low level" (C-like API) because it is more natural to me, and I am liking it so far.

Thanks.

**Comment by c0gent** [comment]
Sure, I should have time today to implement that.

Glad you're enjoying the library. Please let me know if you notice anything else that needs implementing or improvement.

**Comment by c0gent** [comment]
Calling `core::get_program_info(&program, core::ProgramInfo::Binaries)` will now return a `ProgramInfoResult::Binaries(Vec<Vec<u8>>)` Containing one `Vec` of bytes for each device associated with the program.

Please try it out and let me know if it works for you. In case you don't already know, to use the master branch version of `ocl` just change the dependency entry in your `Cargo.toml` to:

```
ocl = { version = "*", git = "https://github.com/cogciprocate/ocl" }
```

**Comment by rNoz** [comment]
Great! You did really well and fast.

I tested the bytes produced with ocl compared with the same kernel built from C++. In case anyone is interested in comparing byte by byte (to test overall validity `diff` works), I used:

```
hexdump -e '16/1 "%3d " "\n"' kernel.cl.bin
```

I will study your commit 3aa2b35  ;)

Thanks!

**Comment by c0gent** [comment]
No problem. Just open another issue if you run into anything else :)

If you have any other general questions about ocl or Rust please feel free to ask on [the ocl gitter channel](https://gitter.im/cogciprocate/ocl).
