### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by usbalbin** [cogciprocate/ocl#94]
First of please bear with me, this is probably my first github issue and I may very well be using this library wrong or simply misunderstanding something. 

However, I find that the following steps lead to a memory leak on my AMD Vega 56 GPU but not Intel 3930k CPU:

1. Create temporary buffer

2. Set buffer as argument to a kernel

3. enqueue kernel without enew() event

At every step in this process the reference counter is increased. This is fine for step 1 and 2. Step 1 is countered by when the buffer is dropped, step 2 when another buffer is set as argument. However step 3 is supposed to be countered by waiting for the event, only we have not specified an event to wait for.

Because of this the counter never reaches zero and the buffer is never freed. Step 1 and 2 behave identically on both my devices however my CPU does not increment the rc on step 3 thus no leak.

Finally, i do not know wether this problem should be the library users, AMD's or the ocl crate's problem but I must say that it at least caught me off guard. I do have a simple example of the leak in action if anyone is interested.

**Comment by usbalbin** [comment]
I guess the important part is this.
Memory leak:
```rust
kernel.set_arg_buf_named("x", Some(&mut buf)).unwrap();
unsafe {    //Enqueue kernel WITHOUT specifying event with enew()
    kernel
        .cmd()
        .gws(size)
        .enq().unwrap();
}
```
No leak:
```rust
kernel.set_arg_buf_named("x", Some(&mut buf)).unwrap();
unsafe {
    let mut event = ocl::Event::empty();
    kernel
        .cmd()
        .enew(&mut event)
        .gws(res.len())
        .enq().unwrap();
    event.wait_for().unwrap();
}
```
Enqueueing the kernel seems to increment the buffers reference counter even if no event is specified.

**Comment by c0gent** [comment]
You could create a repo for it, put it in a [gist](https://gist.github.com) or just paste it here if it's not too long.

**Comment by c0gent** [comment]
Please link/paste all the code so that I can run it exactly the same :)

**Comment by usbalbin** [comment]
Sure here it is https://github.com/usbalbin/mem_leak

**Comment by usbalbin** [comment]
I ported [my code to  C++](https://gist.github.com/usbalbin/44cbf47240940c23698d8278e1d377da) with the C API and the behavior is the same.

**Comment by c0gent** [comment]
Interesting. I haven't had a chance to look into this yet but it sounds like it could be an issue with the drivers. It may be necessary to add a platform-specific workaround for now. I should have time to spend on it later today or tomorrow.

**Comment by usbalbin** [comment]
From the beginning I (wrongly) assumed passing no event when enqueueing kernel would result in a blocking call. Although the [OpenCL documentation](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clEnqueueNDRangeKernel.html) states

> - event
>  Returns an event object that identifies this particular kernel execution instance. Event objects are unique and can be used to identify a particular kernel execution instance later on. **If event is NULL, no event will be created for this kernel execution instance and therefore it will not be possible for the application to query or queue a wait for this particular kernel execution instance.**

which at least gives me a hard time to find a use case for not passing an event. This combined with the fact that my GPU-driver(to my understanding) seems to think that the kernel is referring to the buffer until it has been guaranteed to not be running. Which can only be checked by waiting for an event that in this case does not exist, seems a bit odd.

**Comment by c0gent** [comment]
> clFinish seems to decrease the buffer's reference counter

Yes indeed. It looks like the only reason you're seeing a difference in the reference counts between the `::leak` and `::no_leak` functions in your example is simply because `::print_ref_count` was being called before the kernel command had completed. Adding a call to `Queue::finish` just after enqueuing the kernel allows all commands to complete and the count to be reported accurately. Waiting on an event has the exact same effect.

**Comment by c0gent** [comment]
I'll go ahead and close this issue unless there's anything else.

Please let me know if there's anything else about events, queues, etc. I can help clarify. Contact me on the [ocl gitter channel](https://gitter.im/cogciprocate/ocl) with any questions you might have, I'm happy to help.

**Comment by usbalbin** [comment]
Sure. Thank you very much!
