### ISSUE TITLE
Can Kernel API for example gws take &mut self as the first argument

### ISSUE THREAD

**Issue by asypost** [cogciprocate/ocl#98]
Now the **Kernel** API for example **fn gws<D: Into<SpatialDims>>(self, gws: D) -> Kernel** take **self** as it's first argument,and return self after been called.It's not friendly when **Kernel** instance is used as a field of a Struct.Is it possible to take **&mut self** as it's first argument.
  In other words.It's difficult to cache the Kernel instance for changing it's settings before call it later.

**Comment by c0gent** [comment]
[`Kernel`](https://docs.rs/ocl/0.17.0/ocl/struct.Kernel.html) is about to undergo a series of changes. This will be one of them.

**Comment by c0gent** [comment]
A number of changes to `Kernel` have just landed on master. The details can be found in [`RELEASES.md`](https://github.com/cogciprocate/ocl/blob/master/RELEASES.md). If you have a chance, please try them out and let me know how it goes and if the instructions could use any improvement :)

**Comment by asypost** [comment]
Thanks!I'll give it a try next time.
